### ISSUE TITLE
error using pymc3_loc_model

### ISSUE THREAD

**Issue by rue1996** [BayraktarLab/cell2location#113]
Hi

I am getting an error when l use the pymc3_loc_model :
Code used: from cell2location import run_cell2location
res_dict = run_cell2location(
						sc_data=adata_snrna_raw,
						sp_data=sp_anndata,
						model_name=cell2location.models.base.pymc3_loc_model.Pymc3LocModel,
						verbose=True,
						show_locations=False,
						return_all=True,
						summ_sc_data_args={
							"cluster_col": "cluster_label",
							"selection": "cluster_specificity",
							"selection_specificity": 0.07,
						},
						train_args={
                                                        "mode": 'tracking',
							"n_iter": 20000,
							"learning_rate": 0.005,
							"sample_prior": False,
							"readable_var_name_col": 'SYMBOL',
							"sample_name_col": None,
						},
						model_kwargs={},
						posterior_args={"n_samples": 1000},
						export_args={
							"path": "./results",
							"save_model": False,
							"save_spatial_plots": True,
							"run_name_suffix": "",
							"scanpy_coords_name": "coords",
						},
						ignore_deprecation_exception = True
					)

Error that i am getting; ### Summarising single cell clusters ###
### Training model ###
Traceback (most recent call last):
  File "/scratch/visium_08_10_21/brain_visium_data/run_cell2loc_using_run_cl2/cl2.py", line 114, in <module>
    res_dict = run_cell2location(
  File "/home/.local/lib/python3.9/site-packages/cell2location/run_c2l.py", line 442, in run_cell2location
    mod.track_parameters(
TypeError: track_parameters() got an unexpected keyword argument 'sample_type'

To which i the moved the argument sample_type

Then l got this error: 
### Training model ###
  0%|                                                                                            | 0/21 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/scratch/visium_08_10_21/brain_visium_data/run_cell2loc_using_run_cl2/cl2.py", line 114, in <module>
    res_dict = run_cell2location(
  File "/home/.local/lib/python3.9/site-packages/cell2location/run_c2l.py", line 442, in run_cell2location
    mod.track_parameters(
  File "/home/.local/lib/python3.9/site-packages/cell2location/models/base/pymc3_model.py", line 726, in track_parameters
    self.train(n=n, method="advi", n_type=n_type, n_iter=1, progressbar=False)
  File "/home/.local/lib/python3.9/site-packages/cell2location/models/base/pymc3_model.py", line 232, in train
    with self.model:
AttributeError: 'Pymc3LocModel' object has no attribute 'model'

**Comment by vitkl** [comment]
Hi @rue1996 

Please don't use deprecated pymc3-based workflow. Please install the latest version of cell2location as described here: https://github.com/BayraktarLab/cell2location#installation; and follow the tutorial provided here: https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html

**Comment by rue1996** [comment]
Hi @vitkl 

Looking at the link provided that is how l installed the cell2location version. The tutorial link provided shows this as well: 
![Screenshot (291)](https://user-images.githubusercontent.com/97530114/150666570-f4d50e2c-8aa3-4f63-bedd-2fa603bfbcfb.png)
Does it mean everything under the pymc3 tutorial is deprecated?

The reason why l am using the pymc3-based workflow is because from my previous error you mentioned that NB regression models are not good for the data that l have. I should use other models provided. Could you please let me know, from the tutorial link you sent which tutorial l should follow : i am using allen brain single cell human atlas dataset as my sc reference and 10X visium dataset?

**Comment by vitkl** [comment]
> Does it mean everything under the pymc3 tutorial is deprecated?

Yes, except for the nanostring WTA model.

> sample_name : AAACCCAAGGATTTCC-LKTX_190129_01_A01

This is most likely a cell name, not a 10X reaction name. Regression model and cell2location models will fail if you provide cell and location names as batch_key.
