### ISSUE TITLE
what is tutorial_utils module?

### ISSUE THREAD

**Issue by sadiexiaoyu** [BayraktarLab/cell2location#121]
### Problem

Dear cell2location,

I try to run the code from (https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html#Mapping-human-lymph-node-cell-types-to-10X-Visium)Mapping human lymph node cell types to 10X Visium
When I run code #40 
with mpl.rc_context({'axes.facecolor':  'black'}):
    # select one slide
    slide = select_slide(adata_vis, 'V1_Human_Lymph_Node')

    from tutorial_utils import plot_genes_per_cell_type
    plot_genes_per_cell_type(slide, genes, ctypes);

I got the error report that "No Module named tutorial_utils".
Is this "tutorial_utils" a module of cell2location?
How can I import this module?

**Comment by vitkl** [comment]
Hi @sadiexiaoyu 

You need to copy this function/module from https://github.com/BayraktarLab/cell2location/blob/master/docs/notebooks/tutorial_utils.py. That code will often need customization to your particular dataset, hence it is not added to the cell2location module. You can use it by copying the code into your notebook.
