### ISSUE TITLE
how to get output figures

### ISSUE THREAD

**Issue by sadiexiaoyu** [BayraktarLab/cell2location#122]
### Problem

Hello, cell2location, 
I am running the code from https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html
But I cannot get any figure as the output file.
Do I need additional code for plotting figures?
 

- [ ] I follow the instructions from the [cell2location tutorial (using on scvi-tools)](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html).
- [ ] I have adjusted required hyperparameters to my dataset and tissue `N_cells_per_location` and `detection_alpha`.
- [ ] I have provided 10X reaction/inlet as `batch_key` for reference NB regression.
- [ ] I have checked [Cell2location Community Forum](https://github.com/BayraktarLab/cell2location/discussions), [scvi-tools forum](https://discourse.scvi-tools.org/) and did not find a solution

### Description of the data input and hyperparameters

...

...

#### Single cell reference data: number of cells, number of cell types, number of genes

...

#### Single cell reference data: technology type (e.g. mix of 10X 3' and 5')

...

#### Spatial data: number of locations numbers, technology type (e.g. Visium, ISS, Nanostring WTA)

...

**Comment by vitkl** [comment]
@sadiexiaoyu 

Can you please clarify what this means?
> But I cannot get any figure as the output file.

**Comment by vitkl** [comment]
I am assuming that this is resolved.
