### ISSUE TITLE
Annotated snRNA-seq data - link to access?

### ISSUE THREAD

**Issue by bhavyaac** [BayraktarLab/cell2location#127]
Hello! Thank you for your work on this exciting tool. My question is not regarding the Cell2location tool itself, rather it is about the data in the Cell2location paper.
The Data availability section in the paper states that snRNA-seq data annotated by astrocyte subcluster is available via cellxgene. However, I am unable to find the data on [the cellxgene public portal website](https://cellxgene.cziscience.com/). Could you please provide me with a link to access the annotation?
Thank you!

**Comment by oabayraktar** [comment]
hi, thanks for your interest. this refers to our own cellxgene portal (not the main portal maintained by CZi) and the links were omitted during the manuscript proofing. See https://cell2location.cellgeni.sanger.ac.uk/mouse-brain-astrocytes and the full dataset under https://cell2location.cellgeni.sanger.ac.uk/mouse-brain - both links listed on our pre-print

**Comment by bhavyaac** [comment]
Thank you very much for the information!

**Comment by vitkl** [comment]
The preferred source for this data is our ArrayExpress submission: https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-11114/ and https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-11115/
