### ISSUE TITLE
invalid values error in the GammaPoisson() for Reference data training process

### ISSUE THREAD

**Issue by scarlettcanny0629** [BayraktarLab/cell2location#128]
Hi I encountered the value error saying that 
ValueError: Expected value argument (Tensor of shape (2500, 20925)) to be within the support (IntegerGreaterThan(lower_bound=0)) of the distribution GammaPoisson(), but found invalid values:
tensor([[0.0000, 0.9725, 0.9725,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       device='cuda:0')

when I was trying to train the model on the reference dataset:

from cell2location.models import RegressionModel
mod = RegressionModel(adata_ref)
mod.train(max_epochs=250, batch_size=2500, train_size=1, lr=0.002, use_gpu=True)

The detailed error log is attached.

Currently I have trouble figuring out what caused this error, I am wondering if you could give some suggestions on this issue, thanks a lot!
[simdata1_error.log](https://github.com/BayraktarLab/cell2location/files/8126051/simdata1_error.log)

**Comment by pranzatelli** [comment]
I had this exact problem and found the solution at #120. You have to pass non-normalized/non-log-transformed data.

**Comment by FanZhang9** [comment]
what can i do, if i only got TPM data

**Comment by vitkl** [comment]
Replied in https://github.com/BayraktarLab/cell2location/issues/204#issuecomment-1272416837

**Comment by hezuoxi** [comment]
i use scanpy read the cellranger data why still have this error, i don't know where is wrong
