### ISSUE TITLE
Issue Importing Cell2Location - Completely Clean Env

### ISSUE THREAD

**Issue by pranzatelli** [BayraktarLab/cell2location#129]
- [ x ] I have confirmed this bug exists on the latest version of cell2location. See https://github.com/BayraktarLab/cell2location#installation
- [ x ] I follow the instructions from the [scvi-tools tutorial](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html).

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can run without your data, using public data)

```python
import cell2location
```

```pytb
ImportError: cannot import name '_CONSTANTS' from 'scvi' (/~/conda/envs/cell2loc39/lib/python3.9/site-packages/scvi/__init__.py)
```

Created a brand-new conda env called cell2loc39, did nothing other than "pip install cell2location" and tried to import cell2location. Immediately ran into a problem importing scvi. I didn't find a similar problem in the current issues.

**Comment by adamgayoso** [comment]
This is due to a new release on the scvi-tools side while cell2location needs to make a release to reflect our changes. For now you can first install `pip3 install scvi-tools==0.14.5` and then install cell2location

**Comment by pranzatelli** [comment]
So I did this and am now getting a different ImportError:
`ImportError: cannot import name '_deep_getattr' from 'pyro.infer.autoguide.guides' (/conda/envs/py39c2l/lib/python3.9/site-packages/pyro/infer/autoguide/guides.py)`
Is there a different version of pyro I should install? Is there a list of all version controls necessary or a Docker container I should be using?

**Comment by vitkl** [comment]
Hi @pranzatelli 

Sorry for the delayed response. Are you installing from the GitHub master branch or from pypi? `pip install git+https://github.com/BayraktarLab/cell2location.git#egg=cell2location[tutorials]` or `pip install cell2location`

Only installation from GitHub is valid at the moment. I see that GitHub tests pass https://github.com/BayraktarLab/cell2location/runs/5504910077?check_suite_focus=true today so installation from GitHub master branch should work.

Could it be that you have an issue with `PYTHONNOUSERSITE` on your system?

**Comment by pranzatelli** [comment]
Alright so after some testing, I can confirm that making a new environment and doing nothing more than
'pip install git+https://github.com/BayraktarLab/cell2location.git#egg=cell2location[tutorials]'
works perfectly and my problem has been solved. Thank you both for all your help.
