### ISSUE TITLE
Issue with mod.plot_history graph

### ISSUE THREAD

**Issue by rue1996** [BayraktarLab/cell2location#130]
[modplotQC.pdf](https://github.com/BayraktarLab/cell2location/files/8222477/modplotQC.pdf)
### Problem
I also would like your opinion on my mod.plotQC graph

... [modplot.pdf](https://github.com/BayraktarLab/cell2location/files/8222474/modplot.pdf).
When l plot the mod.plot_history i do not see the blue line showing the trend. I would like to know what could be the reason.  Image attached of the adata_reference 

Thanks 

- [* ] I follow the instructions from the [cell2location tutorial (using on scvi-tools)](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html).
- [ *] I have adjusted required hyperparameters to my dataset and tissue `N_cells_per_location` and `detection_alpha`.
- [* ] I have provided 10X reaction/inlet as `batch_key` for reference NB regression.
- [ *] I have checked [Cell2location Community Forum](https://github.com/BayraktarLab/cell2location/discussions), [scvi-tools forum](https://discourse.scvi-tools.org/) and did not find a solution

### Description of the data input and hyperparameters

...

...

#### Single cell reference data: number of cells, number of cell types, number of genes

... number of cells 46284 cells, number of cell types 21, number of genes, 13174 vars 

#### Single cell reference data: technology type (e.g. mix of 10X 3' and 5')
10X 3'

...

#### Spatial data: number of locations numbers, technology type (e.g. Visium, ISS, Nanostring WTA)

...

**Comment by vitkl** [comment]
You can try adding plt.show() after each plot.

**Comment by vitkl** [comment]
I am assuming that this is resolved.
