### ISSUE TITLE
ValueError when train the regression model using adata_ref

### ISSUE THREAD

**Issue by huangluyujie** [BayraktarLab/cell2location#134]
### Problem

After inputting the unnormalised raw counts, I try to train the regression model using adata_ref. However, it gave back ValueError. 

### the data input
adata_ref.X
<53881x28791 sparse matrix of type '<class 'numpy.float64'>'
	with 66281699 stored elements in Compressed Sparse Row format>
### the parameters
scvi.data.setup_anndata(adata=adata_ref,  labels_key='subCluster' )

mod = RegressionModel(adata_ref)
mod.train(max_epochs=250, batch_size=2500, train_size=1, lr=0.002, use_gpu= True)

### ValueError
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pyro/poutine/trace_struct.py:230, in Trace.compute_log_prob(self, site_filter)
    229 try:
--> 230     log_p = site["fn"].log_prob(
    231         site["value"], *site["args"], **site["kwargs"]
    232     )
    233 except ValueError as e:

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pyro/distributions/conjugate.py:277, in GammaPoisson.log_prob(self, value)
    276 if self._validate_args:
--> 277     self._validate_sample(value)
    278 post_value = self.concentration + value

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/torch/distributions/distribution.py:286, in Distribution._validate_sample(self, value)
    285 if not valid.all():
--> 286     raise ValueError(
    287         "Expected value argument "
    288         f"({type(value).__name__} of shape {tuple(value.shape)}) "
    289         f"to be within the support ({repr(support)}) "
    290         f"of the distribution {repr(self)}, "
    291         f"but found invalid values:\n{value}"
    292     )

ValueError: Expected value argument (Tensor of shape (2500, 28791)) to be within the support (IntegerGreaterThan(lower_bound=0)) of the distribution GammaPoisson(), but found invalid values:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Input In [96], in <cell line: 2>()
      1 # Use all data for training (validation not implemented yet, train_size=1)
----> 2 mod.train(max_epochs=250, batch_size=2500, train_size=1, lr=0.002, use_gpu= True)
      4 # plot ELBO loss history during training, removing first 20 epochs from the plot
      5 mod.plot_history(20)

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/cell2location/models/reference/_reference_model.py:158, in RegressionModel.train(self, max_epochs, batch_size, train_size, lr, **kwargs)
    155 kwargs["train_size"] = train_size
    156 kwargs["lr"] = lr
--> 158 super().train(**kwargs)

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/scvi/model/base/_pyromixin.py:145, in PyroSviTrainMixin.train(self, max_epochs, use_gpu, train_size, validation_size, batch_size, early_stopping, lr, plan_kwargs, **trainer_kwargs)
    135 trainer_kwargs["callbacks"].append(PyroJitGuideWarmup())
    137 runner = TrainRunner(
    138     self,
    139     training_plan=training_plan,
   (...)
    143     **trainer_kwargs,
    144 )
--> 145 return runner()

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/scvi/train/_trainrunner.py:72, in TrainRunner.__call__(self)
     69 if hasattr(self.data_splitter, "n_train"):
     70     self.training_plan.n_obs_training = self.data_splitter.n_train
---> 72 self.trainer.fit(self.training_plan, self.data_splitter)
     73 self._update_history()
     75 # data splitter only gets these attrs after fit

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/scvi/train/_trainer.py:177, in Trainer.fit(self, *args, **kwargs)
    171 if isinstance(args[0], PyroTrainingPlan):
    172     warnings.filterwarnings(
    173         action="ignore",
    174         category=UserWarning,
    175         message="`LightningModule.configure_optimizers` returned `None`",
    176     )
--> 177 super().fit(*args, **kwargs)

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:460, in Trainer.fit(self, model, train_dataloader, val_dataloaders, datamodule)
    455 # links data to the trainer
    456 self.data_connector.attach_data(
    457     model, train_dataloader=train_dataloader, val_dataloaders=val_dataloaders, datamodule=datamodule
    458 )
--> 460 self._run(model)
    462 assert self.state.stopped
    463 self.training = False

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:758, in Trainer._run(self, model)
    755 self.pre_dispatch()
    757 # dispatch `start_training` or `start_evaluating` or `start_predicting`
--> 758 self.dispatch()
    760 # plugin will finalized fitting (e.g. ddp_spawn will load trained model)
    761 self.post_dispatch()

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:799, in Trainer.dispatch(self)
    797     self.accelerator.start_predicting(self)
    798 else:
--> 799     self.accelerator.start_training(self)

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py:96, in Accelerator.start_training(self, trainer)
     95 def start_training(self, trainer: 'pl.Trainer') -> None:
---> 96     self.training_type_plugin.start_training(trainer)

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py:144, in TrainingTypePlugin.start_training(self, trainer)
    142 def start_training(self, trainer: 'pl.Trainer') -> None:
    143     # double dispatch to initiate the training loop
--> 144     self._results = trainer.run_stage()

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:809, in Trainer.run_stage(self)
    807 if self.predicting:
    808     return self.run_predict()
--> 809 return self.run_train()

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:871, in Trainer.run_train(self)
    867 self.train_loop.on_train_epoch_start(epoch)
    869 with self.profiler.profile("run_training_epoch"):
    870     # run train epoch
--> 871     self.train_loop.run_training_epoch()
    873 if self.max_steps and self.max_steps <= self.global_step:
    874     self.train_loop.on_train_end()

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py:499, in TrainLoop.run_training_epoch(self)
    495 # ------------------------------------
    496 # TRAINING_STEP + TRAINING_STEP_END
    497 # ------------------------------------
    498 with self.trainer.profiler.profile("run_training_batch"):
--> 499     batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
    501 # when returning -1 from train_step, we end epoch early
    502 if batch_output.signal == -1:

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py:743, in TrainLoop.run_training_batch(self, batch, batch_idx, dataloader_idx)
    741         self.trainer.lightning_module.untoggle_optimizer(opt_idx)
    742 else:
--> 743     self._curr_step_result = self.training_step(
    744         split_batch, batch_idx, opt_idx, self.trainer.hiddens
    745     )
    747 if self._curr_step_result is None:
    748     # user decided to skip optimization
    749     # make sure to zero grad.
    750     continue

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py:290, in TrainLoop.training_step(self, split_batch, batch_idx, opt_idx, hiddens)
    288 model_ref._results = Result()
    289 with self.trainer.profiler.profile("training_step"):
--> 290     training_step_output = self.trainer.accelerator.training_step(args)
    291     self.trainer.accelerator.post_training_step()
    293 self.trainer.logger_connector.cache_logged_metrics()

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py:204, in Accelerator.training_step(self, args)
    201 args[0] = self.to_device(args[0])
    203 with self.precision_plugin.train_step_context(), self.training_type_plugin.train_step_context():
--> 204     return self.training_type_plugin.training_step(*args)

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py:155, in TrainingTypePlugin.training_step(self, *args, **kwargs)
    154 def training_step(self, *args, **kwargs):
--> 155     return self.lightning_module.training_step(*args, **kwargs)

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/scvi/train/_trainingplans.py:710, in PyroTrainingPlan.training_step(self, batch, batch_idx)
    708     kwargs.update({"kl_weight": self.kl_weight})
    709 # pytorch lightning requires a Tensor object for loss
--> 710 loss = torch.Tensor([self.svi.step(*args, **kwargs)])
    712 return {"loss": loss}

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pyro/infer/svi.py:145, in SVI.step(self, *args, **kwargs)
    143 # get loss and compute gradients
    144 with poutine.trace(param_only=True) as param_capture:
--> 145     loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
    147 params = set(
    148     site["value"].unconstrained() for site in param_capture.trace.nodes.values()
    149 )
    151 # actually perform gradient steps
    152 # torch.optim objects gets instantiated for any params that haven't been seen yet

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pyro/infer/trace_elbo.py:140, in Trace_ELBO.loss_and_grads(self, model, guide, *args, **kwargs)
    138 loss = 0.0
    139 # grab a trace from the generator
--> 140 for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
    141     loss_particle, surrogate_loss_particle = self._differentiable_loss_particle(
    142         model_trace, guide_trace
    143     )
    144     loss += loss_particle / self.num_particles

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pyro/infer/elbo.py:182, in ELBO._get_traces(self, model, guide, args, kwargs)
    180 else:
    181     for i in range(self.num_particles):
--> 182         yield self._get_trace(model, guide, args, kwargs)

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pyro/infer/trace_elbo.py:57, in Trace_ELBO._get_trace(self, model, guide, args, kwargs)
     52 def _get_trace(self, model, guide, args, kwargs):
     53     """
     54     Returns a single trace from the guide, and the model that is run
     55     against it.
     56     """
---> 57     model_trace, guide_trace = get_importance_trace(
     58         "flat", self.max_plate_nesting, model, guide, args, kwargs
     59     )
     60     if is_validation_enabled():
     61         check_if_enumerated(guide_trace)

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pyro/infer/enum.py:75, in get_importance_trace(graph_type, max_plate_nesting, model, guide, args, kwargs, detach)
     72 guide_trace = prune_subsample_sites(guide_trace)
     73 model_trace = prune_subsample_sites(model_trace)
---> 75 model_trace.compute_log_prob()
     76 guide_trace.compute_score_parts()
     77 if is_validation_enabled():

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pyro/poutine/trace_struct.py:236, in Trace.compute_log_prob(self, site_filter)
    234     _, exc_value, traceback = sys.exc_info()
    235     shapes = self.format_shapes(last_site=site["name"])
--> 236     raise ValueError(
    237         "Error while computing log_prob at site '{}':\n{}\n{}".format(
    238             name, exc_value, shapes
    239         )
    240     ).with_traceback(traceback) from e
    241 site["unscaled_log_prob"] = log_p
    242 log_p = scale_and_mask(log_p, site["scale"], site["mask"])

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pyro/poutine/trace_struct.py:230, in Trace.compute_log_prob(self, site_filter)
    228 if "log_prob" not in site:
    229     try:
--> 230         log_p = site["fn"].log_prob(
    231             site["value"], *site["args"], **site["kwargs"]
    232         )
    233     except ValueError as e:
    234         _, exc_value, traceback = sys.exc_info()

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/pyro/distributions/conjugate.py:277, in GammaPoisson.log_prob(self, value)
    275 def log_prob(self, value):
    276     if self._validate_args:
--> 277         self._validate_sample(value)
    278     post_value = self.concentration + value
    279     return (
    280         -log_beta(self.concentration, value + 1)
    281         - post_value.log()
    282         + self.concentration * self.rate.log()
    283         - post_value * (1 + self.rate).log()
    284     )

File /data2/hlyj/miniconda3/envs/cell2loc_env/lib/python3.9/site-packages/torch/distributions/distribution.py:286, in Distribution._validate_sample(self, value)
    284 valid = support.check(value)
    285 if not valid.all():
--> 286     raise ValueError(
    287         "Expected value argument "
    288         f"({type(value).__name__} of shape {tuple(value.shape)}) "
    289         f"to be within the support ({repr(support)}) "
    290         f"of the distribution {repr(self)}, "
    291         f"but found invalid values:\n{value}"
    292     )

ValueError: Error while computing log_prob at site 'data_target':
Expected value argument (Tensor of shape (2500, 28791)) to be within the support (IntegerGreaterThan(lower_bound=0)) of the distribution GammaPoisson(), but found invalid values:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')
                Trace Shapes:                      
                 Param Sites:                      
                Sample Sites:                      
       per_cluster_mu_fg dist            | 90 28791
                        value            | 90 28791
                     log_prob            |         
      detection_mean_y_e dist            |  1     1
                        value            |  1     1
                     log_prob            |         
  s_g_gene_add_alpha_hyp dist            |         
                        value            |         
                     log_prob            |         
       s_g_gene_add_mean dist            |  1     1
                        value            |  1     1
                     log_prob            |         
s_g_gene_add_alpha_e_inv dist            |  1     1
                        value            |  1     1
                     log_prob            |         
            s_g_gene_add dist            |  1 28791
                        value            |  1 28791
                     log_prob            |         
         alpha_g_phi_hyp dist            |         
                        value            |         
                     log_prob            |         
         alpha_g_inverse dist            |  1 28791
                        value            |  1 28791
                     log_prob            |         
             data_target dist 2500 28791 |         
                        value 2500 28791 |

**Comment by vitkl** [comment]
Hi

Are the provided values integer counts? Does the data matrix have NaN?

This error indicates a issue with the count matrix.

Probably unrelated to the error but in general I would recommend doing gene
selection as shown in the tutorial (as opposed to keeping 28k genes).

Vitalii

**Comment by huangluyujie** [comment]
>

**Comment by huangluyujie** [comment]
Hi
The h5ad file loaded above was transformed from Seurat object using function saveH5seurat. After the ValueError, I tried to export the seurat object to 10X format and read it directly, and now it works. So maybe some error occurred during the process of saveH5seurat transformation.

**Comment by FanZhang9** [comment]
Hi, what if i only got the TPM data . How can I ran this mapping .

**Comment by vitkl** [comment]
@FanZhang9 - replied in https://github.com/BayraktarLab/cell2location/issues/204#issuecomment-1272416837
