### ISSUE TITLE
ModuleNotFoundError in singularity image in version cell2location-v0.06-alpha.sif

### ISSUE THREAD

**Issue by CeliaLerma** [BayraktarLab/cell2location#137]
Hi,

I am trying to run the new tutorial of cell2location in the latest singularity image version (cell2location-v0.06-alpha.sif) and I am encountering this problem:

``` 
singularity shell cell2location-v0.06-alpha.sif
python
import cell2location
from cell2location.utils.filtering import filter_genes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cell2location.utils'
```
Am I using a wrong image? Which one should I use? I have also tried to run it using v0.05 and it still does not work.

Thank you for your time.

**Comment by vitkl** [comment]
Please don't use the singularity image for now. Follow the
installation instructions in the readme - which should generally work.

**Comment by CeliaLerma** [comment]
Thanks for the quick reply! I will try with the conda enviroment instead

**Comment by CeliaLerma** [comment]
Hi,
As you suggested last time, I am not using the singularity image anymore and I have created a new environment to work with but I am encountering some problems still.

I created an environment this morning and installed:
```
conda create -n cell2loc python=3.9 -y
pip install git+https://github.com/BayraktarLab/cell2location
```

But this error pops up:
```
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType: None
Global seed set to 0
loaded inf_aver
read and modif visium slide
calculated QC metrics
Traceback (most recent call last):
 File "/gpfs/bwfor/home/hd/hd_hd/hd_td263/Visium_pipeline/scripts_cell2loc/cell2loc_mapping.py", line 72, in <module>
   scvi.data.setup_anndata(adata=adata, batch_key="sample")
AttributeError: module 'scvi.data' has no attribute 'setup_anndata'
```


Is there anything else that I should take into account when creating the environment that is missing?

Thank you for your time

**Comment by vitkl** [comment]
Hi again

can you try this solution?

https://github.com/BayraktarLab/cell2location/issues/142#issuecomment-1100842578

**Comment by CeliaLerma** [comment]
Hi,
Thanks for the response. I have used the export PYTHONNOUSERSITE="someletters" and also got the jax error. After installing the corrected jax versions I still get the same error.
```
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher r$
NoneType: None
Global seed set to 0
loaded inf_aver
read and modif visium slide
calculated QC metrics
Traceback (most recent call last):
  File "/gpfs/bwfor/home/hd/hd_hd/hd_td263/Visium_pipeline/scripts_cell2loc/cell2loc_mapping.py", line 72, in $
    scvi.data.setup_anndata(adata=adata, batch_key="sample")
AttributeError: module 'scvi.data' has no attribute 'setup_anndata'
```
These are my package versions:
```
scvi-tools 0.16.0
cell2location 0.8a0
```
Are thses the correct ones?

Thanks!
