### ISSUE TITLE
Issues with gpu usage 

### ISSUE THREAD

**Issue by MertDemirdizen** [BayraktarLab/cell2location#140]
Hi,
Thank you for providing such a great tool. I am pretty new in python so my problems might be so dumb. 

I want to use cell2location with my data but I could not figure out how to install it. I installed Ubuntu 20.04.4 LTS, I installed miniconda, and installed cell2location. The problem with Ubuntu is it does not see my Nvidia card, I tried different solutions but I could not fix it. 

I am using Windows10, where my graphic card is seen, I created an isolated environment at anaconda. At mod = RegressionModel(adata_ref) step, I am getting AssertionError: Torch not compiled with CUDA enabled error. I again tried different solutions for this and I could not fix it.

I tried google colab, but I am getting installing and importing errors. I checked your issues section, found #136 and I could not make it fixed with your last solution.

I really need to use the package urgently. I am sure that I am missing some basics, but if you can lead me to use, I would be appreciated. 

Thank you very much in advance.

**Comment by vitkl** [comment]
Hi

I can't give an exhaustive reply now but to use the GPU on Ubuntu you need
to install the Nvidia GPU drivers, CUDA and a few other things - but I
never did it myself so can only give limited recommendations. This is not a
python issue.


If you have sudo access it should be relatively straightforward. You can
find which apt-get packages you need by looking at cell2location docker
recipe and at Nvidia container that we start with. In principle you can
build cell2location docker container on your system (that way it will have
latest cell2location).

**Comment by vitkl** [comment]
Maybe @yozhikoff has more detailed recommendations because he used cell2location on his local PC.

**Comment by yozhikoff** [comment]
@MertDemirdizen 

1) If you want to use cell2locafion (or pytorch in general) on Ubuntu, you need to install NVIDIA graphics card drivers. You can use [this](https://linuxconfig.org/how-to-install-the-nvidia-drivers-on-ubuntu-20-04-focal-fossa-linux) tutorial for example. You don't need to install CUDA manually, it is included in the pytorch distribution. 

2) In the Windows case it seems you have CPU-only pytorch version. You can install the GPU-version from [here](https://pytorch.org/get-started/locally/). 


Both options of course work only if you have an NVIDIA graphics card.

**Comment by MertDemirdizen** [comment]
Thank you for your quick and helpful replies!
I have NVIDIA graphic card, I tried to install drivers in Ubuntu but they did not work. I will both try this tutorial for Ubuntu and install pytorch version for Windows.
I will let you know about the outcomes.

**Comment by MertDemirdizen** [comment]
I could not handle for Ubuntu but I installed pytorch version for Windows and it is working!
Thank you so much for your help.
