### ISSUE TITLE
plot spatial QC errors

### ISSUE THREAD

**Issue by wangjiawen2013** [BayraktarLab/cell2location#147]
Hello cell2location:
I can run cell2location tutorial successfully, but when I ran cell2location on my own data, the following error occurred:
In [71]: fig = mod.plot_spatial_QC_across_batches()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [71], in <cell line: 1>()
----> 1 fig = mod.plot_spatial_QC_across_batches()

File ~/programs/miniconda3/envs/spatial/lib/python3.8/site-packages/cell2location/models/_cell2location_model.py:290, in Cell2location.plot_spatial_QC_across_batches(self)
    288 # plot, iterating across samples
    289 for i, s in enumerate(samples):
--> 290     sp_data_s = select_slide(adata, s, batch_key=batch_key)
    291     scanpy.pl.spatial(
    292         sp_data_s,
    293         cmap="magma",
   (...)
    301         show=False,
    302     )
    303     axs[0, i].title.set_text(cell_type + "\n" + s)

File ~/programs/miniconda3/envs/spatial/lib/python3.8/site-packages/cell2location/utils/__init__.py:19, in select_slide(adata, s, batch_key)
     17 slide = adata[adata.obs[batch_key].isin([s]), :].copy()
     18 s_keys = list(slide.uns["spatial"].keys())
---> 19 s_spatial = np.array(s_keys)[[s in k for k in s_keys]][0]
     21 slide.uns["spatial"] = {s_spatial: slide.uns["spatial"][s_spatial]}
     23 return slide

File ~/programs/miniconda3/envs/spatial/lib/python3.8/site-packages/cell2location/utils/__init__.py:19, in <listcomp>(.0)
     17 slide = adata[adata.obs[batch_key].isin([s]), :].copy()
     18 s_keys = list(slide.uns["spatial"].keys())
---> 19 s_spatial = np.array(s_keys)[[s in k for k in s_keys]][0]
     21 slide.uns["spatial"] = {s_spatial: slide.uns["spatial"][s_spatial]}
     23 return slide

TypeError: 'in <string>' requires string as left operand, not numpy.int8

**Comment by vitkl** [comment]
Hi @wangjiawen2013 

This code subsets anndata object with multiple spatial sections/samples. Generally the `adata.obs` column specifying batch shares identifiers with `slide.uns["spatial"].keys()`. This doesn't not seem to be the case in your object. You need to find and use `adata.obs` column with identifiers matching `slide.uns["spatial"].keys()` or copy and edit the `select_slide` function to fit your object.

**Comment by vitkl** [comment]
I am assuming that this is resolved.
