### ISSUE TITLE
Failed to import cell2location in tutorial when colab has an update

### ISSUE THREAD

**Issue by yxiaobme** [BayraktarLab/cell2location#150]
Every time Colab has an update (with python, CUDA, matplotlib etc), I have a hard time to import cell2location because of dependencies. Can the developers build a virtual environment of cell2location?

I could run through the cell2location tutorial on lymph node until April 20. (https://colab.research.google.com/github/BayraktarLab/cell2location/blob/master/docs/notebooks/cell2location_tutorial.ipynb)
But today, I failed to import cell2location when i ran "Loading packages" session in the cell2location colab tutorial:
```python
import sys

!pip install --quiet git+https://github.com/BayraktarLab/cell2location#egg=cell2location[tutorials]

import scanpy as sc
import anndata
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import matplotlib as mpl

import cell2location
import scvi

from matplotlib import rcParams
rcParams['pdf.fonttype'] = 42 # enables correct plotting of text
import seaborn as sns
```

Error message:
```pytb
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Global seed set to 0
```

I tried again and again with installing those packages by specifying the version number, but keep getting more and more dependency problems. It seems that colab automatically load python v3.7 now. 

Please help!

**Comment by vitkl** [comment]
Thanks for using cell2location!

The issue you observe comes from the Colab platform. As far as I am aware it is impossible to create a conda environment (aka virtual environment) in Colab. You can try creating a fully isolated conda environment by following default installation instructions: https://github.com/BayraktarLab/cell2location#installation (including PYTHONNOUSERSITE option).

**Comment by yxiaobme** [comment]
> Thanks for using cell2location!
> 
> The issue you observe comes from the Colab platform. As far as I am aware it is impossible to create a conda environment (aka virtual environment) in Colab. You can try creating a fully isolated conda environment by following default installation instructions: https://github.com/BayraktarLab/cell2location#installation (including PYTHONNOUSERSITE option).

Hi Vitkl, 
are you able to run the cell2location tutorials in colab this month? I tried both tuorials (one on human lymph node, one on mouse brain) but both failed at the installation step. Maybe it's time to update the cell2location tutorial.
