### ISSUE TITLE
Performance reduction when training the Cell2location model with CPU in the latest version 

### ISSUE THREAD

**Issue by tomasgomes** [BayraktarLab/cell2location#152]
Hello! We  (@AMaynard10 and I) have been running successfully cell2location with snRNA-seq and Visium data, solely using CPUs. The slower steps when doing this are training the regression and Cel2location models, each taking ~1-3h with our data, using version 0.6a0 and scvi-tools version 0.14.3.

Recently we have tried re-running our code (very similar to the tutorial) with the updated cell2location and scvi-tools (versions 0.8a0 and 0.16.1, respectively). For the same datasets, the regression training took approximately the same time, but training the Cell2location model became up to 10 times slower (taking up to 40h), using the same system, at similar times (even simultaneously). 

The code below is what we've used to train the Cell2location model in both versions, and almost directly taken from the tutorial.

```python
# create and train the model
mod2 = cell2location.models.Cell2location(
    vis, cell_state_df=inf_aver,
    # the expected average cell abundance: tissue-dependent
    # hyper-prior which can be estimated from paired histology:
    N_cells_per_location=25,
    # hyperparameter controlling normalisation of
    # within-experiment variation in RNA detection (using default here):
    detection_alpha=200
)

mod2.train(max_epochs=15000,
          # train using full data (batch_size=None)
          batch_size=None,
          # use all data points in training because
          # we need to estimate cell abundance at all locations
          train_size=1,
          use_gpu=False)

# plot ELBO loss history during training, removing first 100 epochs from the plot
mod2.plot_history(1000)
plt.legend(labels=['full data training']);
```

Are there any options that allow us to tune/improve CPU usage?

Thanks in advance and for the very useful tool!

**Comment by adamgayoso** [comment]
This is interesting, @vitkl did you add anything new?

@tomasgomes can you try installing the latest version of scvi-tools (https://github.com/scverse/scvi-tools) on the master branch?

It will work with cell2location just fine, I'm wondering if the issue is related to pytorch lightning

**Comment by vitkl** [comment]
Hi @tomasgomes 

Thanks for reporting here! 

I indeed have not introduced any changes to the model or inference. The difference probably comes from recent changes to pyro, scvi-tools, pytorch lightning. Could you try what @adamgayoso suggested (also reinstalling the latest master branch cell2location)?

**Comment by vitkl** [comment]
Please try installing the just released cell2location version (v0.1) as described here https://github.com/BayraktarLab/cell2location#installation
Let's see if the speed issue still persists and I will try looking into pyro as a potential reason.

**Comment by vitkl** [comment]
>  I found that if I train a new regression model and use that for cell2location modelling I end up with reduced performance

Do you mean loadings regression model output, then creating a new instance of cell2location and training this new instance? The saved regression model class instance should be completely independent from newly created cell2location class instance. Maybe loading the model affects which package version are loaded? 

I principle you don't actually need to load the regression model - you can just read the H5AD object with results (or simply save reference expression signatures as a data frame). If you don't load the regression model and don't train the regression model - do you get the same reduced performance?

**Comment by vitkl** [comment]
Hi @tomasgomes 

Did you solve this?

**Comment by vitkl** [comment]
I am assuming that this is resolved.
