### ISSUE TITLE
Error: 'cell2location' is not a package while importing libraries. 

### ISSUE THREAD

**Issue by Archanayd** [BayraktarLab/cell2location#153]
Hi, 
Thanks for this useful tool. I am currently trying to run Cell2location on my datasets. I have installed the cell2location as directed on the installation instructions. It was also successfully installed and it was working just fine. Suddenly, today its throwing the 'ModuleNotFoundError' while importing the package The error is as follows: "ModuleNotFoundError: No module named 'cell2location.utils'; 'cell2location' is not a package".  
I tried to reinstall the package and tried this on another computer as well but I get the same error. I can confirm I am in the 'cell2loc_env' while running the python script. 

Archana

- [ ] I have confirmed this bug exists on the latest version of cell2location. See https://github.com/BayraktarLab/cell2location#installation
- [ ] I follow the instructions from the [scvi-tools tutorial](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html).

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can run without your data, using public data)

```python
import sys
import scanpy as sc
import anndata
import pandas as pd
import numpy as np
import os
import gc

# this line forces theano to use the GPU and should go before importing cell2location
os.environ["THEANO_FLAGS"] = 'device=cuda0,floatX=float32,force_device=True'
# if using the CPU uncomment this:
#os.environ["THEANO_FLAGS"] = 'device=cpu,floatX=float32,openmp=True,force_device=True'

import cell2location

import matplotlib as mpl
from matplotlib import rcParams
import matplotlib.pyplot as plt
import seaborn as sns

# silence scanpy that prints a lot of warnings
import warnings
warnings.filterwarnings('ignore')
```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 14>()
     10 os.environ["THEANO_FLAGS"] = 'device=cuda0,floatX=float32,force_device=True'
     11 # if using the CPU uncomment this:
     12 #os.environ["THEANO_FLAGS"] = 'device=cpu,floatX=float32,openmp=True,force_device=True'
---> 14 import cell2location
     16 import matplotlib as mpl
     17 from matplotlib import rcParams

File ~/Documents/Arch_work/spinal_cord/ST_cell2location/cell2location.py:33, in <module>
     24 #import gc
     25 
     26 # this line forces theano to use the GPU and should go before importing cell2location
     27 #os.environ["THEANO_FLAGS"] = 'device=cuda0,floatX=float32,force_device=True'
     28 # if using the CPU uncomment this:
     29 #os.environ["THEANO_FLAGS"] = 'device=cpu,floatX=float32,openmp=True,force_device=True'
     31 import cell2location
---> 33 from cell2location.utils.filtering import filter_genes
     34 from cell2location.models import RegressionModel
     35 from cell2location.utils import select_slide

ModuleNotFoundError: No module named 'cell2location.utils'; 'cell2location' is not a package

<img width="928" alt="Screen Shot 2022-05-12 at 4 14 55 PM" src="https://user-images.githubusercontent.com/14109213/168160748-d5ca1633-844e-4ec7-a178-075c25f4ae66.png">

**Comment by adamgayoso** [comment]
I believe the issue is that you have a file called cell2location. I would try renaming this file.

**Comment by Archanayd** [comment]
Hi @adamgayoso. Yes, that was it. I didn't realize there was a duplicate file called cell2location.py in the same directory. Thank you so much.
