### ISSUE TITLE
Fail to import LocationModelWTA

### ISSUE THREAD

**Issue by GoodSuun** [BayraktarLab/cell2location#162]
- [x] I have confirmed this bug exists on the latest version of cell2location. See https://github.com/BayraktarLab/cell2location#installation
- [x] I follow the instructions from the [scvi-tools tutorial](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html).

---
We installed your Cell2Location Docker. When we tried to test 'LocationModelWTA' model, got an error. Please tell us how to fix it. Thanks a lot.
**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can run without your data, using public data)

```python
# Your code here
```
cell2location.run_c2l.run_cell2location(meanExpression_sc, adata_wta,
        model_name=cell2location.models.LocationModelWTA,
        train_args={'use_raw': False},
        model_kwargs={
        "Y_data" : counts_negativeProbes,
        "cell_number_prior" : {'cells_per_spot': counts_nuclei, 'factors_per_spot': 6, 'combs_per_spot': 3},
        "cell_number_var_prior" : {'cells_mean_var_ratio': 1, 'factors_mean_var_ratio': 1, 'combs_mean_var_ratio': 1}})
```pytb
[Paste the error output produced by the above code here]
```
AttributeError: module 'cell2location.models' has no attribute 'LocationModelWTA'

**Comment by vitkl** [comment]
Hi @GoodSuun 

This model was permanently removed from the package. Please use SpaceJam (https://github.com/vitkl/SpaceJam/blob/main/notebooks/02_cell2location_map_celltypes_MultiExperimentHierarchicalGeneLevel.ipynb) combined with cell2location singularity image (previous version v0.06): https://cell2location.readthedocs.io/en/latest/dockersingularity.html#using-singularity-image

This model is better at correcting batch effects in the Nanostring data. It will also be moved to the same scvi-tools+pyro interface as main cell2location model by the end of summer.

@AlexanderAivazidis can help with further questions

**Comment by GoodSuun** [comment]
Hi, Alexander,
       We'd like to test your Cell2LocationWTA model. Can you tell me how to use your singularity image on slurm without GPU? Thank you so much in advance.

Best regards,

Lianshui


***@***.***
 
From: Vitalii Kleshchevnikov
Date: 2022-05-28 07:05
To: BayraktarLab/cell2location
CC: GoodSuun; Mention
Subject: Re: [BayraktarLab/cell2location] Fail to import LocationModelWTA (Issue #162)
Hi @GoodSuun
This model was permanently removed from the package. Please use SpaceJam (https://github.com/vitkl/SpaceJam/blob/main/notebooks/02_cell2location_map_celltypes_MultiExperimentHierarchicalGeneLevel.ipynb) combined with cell2location singularity image (previous version v0.06): https://cell2location.readthedocs.io/en/latest/dockersingularity.html#using-singularity-image
This model is better at correcting batch effects in the Nanostring data. It will also be moved to the same scvi-tools+pyro interface as main cell2location model by the end of summer.
@AlexanderAivazidis can help with further questions

**Comment by vitkl** [comment]
@GoodSuun 

you can simply remove GPU arguments and tell the cell2location workflow to not use the GPU use_gpu=False:

```
bsub -q queue_name -M60000 \
  -R"select[mem>60000] rusage[mem=60000] span[hosts=1]"  \
  -Is \
  /bin/singularity exec \
  --no-home  \
  -B /nfs/working_directory:/working_directory \
  path/to/cell2location-v0.06-alpha.sif \
  /bin/bash -c "cd /working_directory && HOME=$(mktemp -d) jupyter notebook --notebook-dir=/working_directory --NotebookApp.token='cell2loc' --ip=0.0.0.0 --port=1237 --no-browser --allow-root"
```
