### ISSUE TITLE
Fail to import run_regression

### ISSUE THREAD

**Issue by TaoShiyue** [BayraktarLab/cell2location#163]
Hi!
I'm trying to estimate expression signatures, but some problems happened.
when I run 'from cell2location import run_regression', then I got the error:

Traceback (most recent call last):
  File "/Users/taoshiyue/PycharmProjects/st_cpdb/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-37-cdd635c2fe96>", line 1, in <cell line: 1>
    from cell2location import run_regression
ImportError: cannot import name 'run_regression' from 'cell2location' (/Users/taoshiyue/PycharmProjects/st_cpdb/venv/lib/python3.9/site-packages/cell2location/__init__.py)

Is there something wrong with my installation(I installed the just released cell2location version (v0.1))? 
Please help me! Thanks a lot.

Best
Shiyue

**Comment by vitkl** [comment]
Hi @TaoShiyue 

Most likely your environment is broken. Please try recreating the conda environment as described in https://github.com/BayraktarLab/cell2location#installation including `export PYTHONNOUSERSITE="literallyanyletters"` option.

**Comment by TaoShiyue** [comment]
Thanks for your reply! I will try to recreate the conda environment.
