### ISSUE TITLE
multi-samples integration

### ISSUE THREAD

**Issue by wangjiawen2013** [BayraktarLab/cell2location#164]
Hi,
I am using cell2location to deconvolution my single cell datasets. Now I have four spatial samples and I have concatenated them in one object. Can I run them together using
cell2location.models.Cell2location.setup_anndata(adata=adata_vis, layers="counts",batch_key="sample") ?
In the tutorial its "cell2location.models.Cell2location.setup_anndata(adata=adata_vis, batch_key="sample")", but there are only one sample in adata_vis, so I wanna know if it supports more samples.

**Comment by vitkl** [comment]
Hi @wangjiawen2013 

Cell2location indeed supports the integration of multiple batches. You just need to provide the a data.obs column containing batch info as batch_key.

**Comment by wangjiawen2013** [comment]
Thanks! @vitkl 
Both bbknn and scvi-tools can be used remove batch effects in single cell data. It was said that sptial datasets were integrated using bbknn in cell2location nature method paper. Can we use scvi-tools to integration spatial datasets ?

**Comment by vitkl** [comment]
Spatial datasets were NOT integrated using BBKNN in the cell2location paper. Cell2location model itself integrates multiple samples (see main text methods section).

scvi-tools is a framework that allows implementation of a wide range of model (including cell2location).

You could be referring to [scVI](https://docs.scvi-tools.org/en/stable/api/reference/scvi.model.SCVI.html#scvi.model.SCVI) autoencoder method. It is not necessary to use that method to use cell2location. In addition, scVI was not tested on multi-cell spatial data.

**Comment by vitkl** [comment]
I am assuming that this is resolved.
