### ISSUE TITLE
multi batches spatial datasets

### ISSUE THREAD

**Issue by wangjiawen2013** [BayraktarLab/cell2location#165]
Hi,
I am using cell2location to deconvolution my single cell datasets. Now I have four spatial samples and I have concatenate them in one object. Can I run them together using
cell2location.models.Cell2location.setup_anndata(adata=adata, layers="counts",batch_key="sample") ?
In the tutorial its "cell2location.models.Cell2location.setup_anndata(adata=adata_vis, batch_key="sample")", but there are only one sample in adata_vis, so I wanna know if it supports more samples.

**Comment by vitkl** [comment]
This is a duplicate
