### ISSUE TITLE
how to install cell2location on windows by anaconda3

### ISSUE THREAD

**Issue by Ziyu-Mu** [BayraktarLab/cell2location#167]
### Problem

I'm new to python so there're lots of questions for installing this on windows.
I don't even know should I use cmd or anaconda prompt....
But anyway I used cmd and these happened:
Fisrt, I found out that"export PYTHONNOUSERSITE="literallyanyletters"is for Linux. For windows we should use "set" instead of "export". So should I run this on windows?
Second, I had trouble use conda activate. After I ran this, it told me to use conda init <shell> and restart. But there is no use, the same error happened over and over again.
Third, then I found out I could just use activate instead of conda activate. But I don't know if there's anything wrong by using this. And even so, I still failed to pip it.QAQ

So, I want a detailed guide for this on windows. 
And can I just use pip install ...? will this cause a problem?
I really appreciate the help. Thank you.

**Comment by vitkl** [comment]
Hi @Ziyu-Mu 

This question can be interpreted as a general question about using scvi-tools on Windows. Please check https://discourse.scverse.org/ and ask your question there.

**Comment by Ziyu-Mu** [comment]
Thanks for your help!

**Comment by Ziyu-Mu** [comment]
> Hi @Ziyu-Mu
> 
> This question can be interpreted as a general question about using scvi-tools on Windows. Please check https://discourse.scverse.org/ and ask your question there.

Thanks for youe help! @vitkl
