### ISSUE TITLE
Error in saving the signature output 

### ISSUE THREAD

**Issue by archanabhardwaj** [BayraktarLab/cell2location#169]
Please use the template below to post a question to https://discourse.scverse.org/c/ecosytem/cell2location/. 

### Problem

I am trying to save the reference signature result. Trained worked without any issue on the single cell data 

**Out[163]: RegressionBackgroundDetectionTech model with the following params: 
n_factors: 7 
n_batch: 2 
Training status: Trained**

In [169]: # In this section, we export the estimated cell abundance (summary of the posterior distribution).
     ...: adata_ref = mod.export_posterior(
     ...:     adata_ref, sample_kwargs={ 'use_gpu': True}
     ...: )
     ...: 
Sampling local variables, batch:   0%|                                                      | 0/2 [00:00<?, ?it/s]
Sampling global variables, sample: 100%|███████████████████████████████████████| 999/999 [00:07<00:00, 138.03it/s]

In [170]: mod.save(f"{ref_run_name}", overwrite=True)
     ...: 

In [171]: adata_file = f"{ref_run_name}/sc.h5ad"
 
I am getting error while saving the result file : 

**adata_ref.write(adata_file)**

File ~/.conda/envs/cell2loc_env/lib/python3.9/site-packages/anndata/_io/specs/registry.py:24, in write_spec.<locals>.decorator.<locals>.wrapper(g, k, *args, **kwargs)
     22 @wraps(func)
     23 def wrapper(g, k, *args, **kwargs):
---> 24     result = func(g, k, *args, **kwargs)
     25     g[k].attrs.setdefault("encoding-type", spec.encoding_type)
     26     g[k].attrs.setdefault("encoding-version", spec.encoding_version)

File ~/.conda/envs/cell2loc_env/lib/python3.9/site-packages/anndata/_io/specs/methods.py:259, in write_raw(f, k, raw, dataset_kwargs)
    257 g = f.create_group(k)
    258 write_elem(g, "X", raw.X, dataset_kwargs=dataset_kwargs)
--> 259 write_elem(g, "var", raw.var, dataset_kwargs=dataset_kwargs)
    260 write_elem(g, "varm", dict(raw.varm), dataset_kwargs=dataset_kwargs)

File ~/.conda/envs/cell2loc_env/lib/python3.9/site-packages/anndata/_io/utils.py:220, in report_write_key_on_error.<locals>.func_wrapper(elem, key, val, *args, **kwargs)
    218 else:
    219     parent = _get_parent(elem)
--> 220     raise type(e)(
    221         f"{e}\n\n"
    222         f"Above error raised while writing key {key!r} of {type(elem)} "
    223         f"to {parent}"
    224     ) from e

ValueError: '_index' is a reserved name for dataframe columns.

Above error raised while writing key 'var' of <class 'h5py._hl.group.Group'> to /

...

- [x] I follow the instructions from the [cell2location tutorial (using on scvi-tools)](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html).
- [x] I have adjusted required hyperparameters to my dataset and tissue `N_cells_per_location` and `detection_alpha`.
- [ ] I have provided 10X reaction/inlet as `batch_key` for reference NB regression.
- [x] I have checked [scverse Discourse](https://discourse.scverse.org/c/ecosytem/cell2location/) and [old Cell2location Community Forum](https://github.com/BayraktarLab/cell2location/discussions), and did not find a solution.

**Comment by vitkl** [comment]
Hi @archanabhardwaj 

Please check that your object does not have `_index` columns in adata.var. Cell2location should not be adding this column. Try saving the object before running the regression model.

**Comment by vitkl** [comment]
I am assuming that this is resolved.
