### ISSUE TITLE
plot_spatial does not work when one of the cell types has exactly 0 abundance

### ISSUE THREAD

**Issue by vitkl** [BayraktarLab/cell2location#17]
<img width="837" alt="Screenshot 2020-12-30 at 12 44 47" src="https://user-images.githubusercontent.com/22567383/103353110-dcd2f380-4a9f-11eb-91b7-86735d0ac0cd.png">

@yozhikoff please have a look at this

Changing the condition to `if min_value > max_value:` results in no errors but an empty plot for all cell types. 

I think this can be resolved if we change how max_color_quantile threshold is applied for this special case of all 0.

You can reproduce this by taking demo notebook results are setting all values for one cell type to 0 (`slide.obs[sel_clust_col[0]] = 0`).

**Comment by wangjiawen2013** [comment]
Hi, how to change the figure size and font size of the legend when ploting ? here is my plot, the font is too big:
![1662219265655](https://user-images.githubusercontent.com/29703450/188277773-1bc95f08-d828-455c-a3c4-9722cd680e08.png)

**Comment by wangjiawen2013** [comment]
Thanks!
and I have another question, some color bar are lack of ticks, such as c4 and c5, where are the min_color_intensity ticks ?
![企业微信截图_16624343746006](https://user-images.githubusercontent.com/29703450/188540018-49a2c99d-6c58-40e7-8997-fe7043ed8775.png)
