### ISSUE TITLE
Question about numerically synthesizing mouse brain spatial dataset

### ISSUE THREAD

**Issue by ZhanYangen** [BayraktarLab/cell2location#172]
### Problem

Hi, thanks for providing such a useful tool. I encountered a source data problem when running the code for synthetic data in cell2location_paper/notebooks/benchmarking/synthetic_data_construction_improved_real_mg.ipynb. I had downloaded the spatial dataset from https://drive.google.com/drive/folders/1UfMe_uTS2yV9ErQA_iGBa4oCDYlFhtWN?usp=sharing.
In the following code:
`gene_level_df = pd.DataFrame(adata_vis.uns['mod']['post_sample_means']['gene_level'],
                          index=adata_vis.uns['mod']['var_names'],
                          columns=['gene_level'])`
`adata_vis` is the spatial dataset "sp.h5ad".
After reading the whole synthesizing code, I believe that `adata_vis.uns['mod']['post_sample_means']['gene_level']` here refers to the parameter **m_g** as described in the cell2location paper.
However, I found that there is no `['gene_level']` from `adata_vis.uns['mod']['post_sample_means']` in "sp.h5ad". But there does exist `['m_g']` from `adata_vis.uns['mod']['post_sample_means']`. So I tried to use this data instead.
In the following visualization process: `plt.hist(gene_level_df.values.flatten(), bins=100)`
The example results are as follows:
![image](https://user-images.githubusercontent.com/77531882/175016791-6cd5471e-ef62-4ecf-815f-951c654376b5.png)
But I get results as follows when using `['m_g']`:
![image](https://user-images.githubusercontent.com/77531882/175017043-65a2aff0-ea80-4d14-af2e-fffea05523c2.png)
While the mean, alpha, beta differ a little in these two images, their overall trends are similar. I wonder if it is ok that I use this `['m_g']` to generate the synthetic dataset.

- [x] I follow the instructions from the [cell2location tutorial (using on scvi-tools)](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html).
- [ ] I have adjusted required hyperparameters to my dataset and tissue `N_cells_per_location` and `detection_alpha`.
- [ ] I have provided 10X reaction/inlet as `batch_key` for reference NB regression.
- [x] I have checked [scverse Discourse](https://discourse.scverse.org/c/ecosytem/cell2location/) and [old Cell2location Community Forum](https://github.com/BayraktarLab/cell2location/discussions), and did not find a solution.

**Comment by vitkl** [comment]
Hi @ZhanYangen 

>  I wonder if it is ok that I use this ['m_g'] to generate the synthetic dataset.

Yes please do that. ['gene_level'] comes from an old version of cell2location (pre 2021). You should get roughly similar result - that correction of sn to Visium effect requires the m_g parameter.

**Comment by ZhanYangen** [comment]
@vitkl Got it. Thanks!
