### ISSUE TITLE
QC history plot error 

### ISSUE THREAD

**Issue by archanabhardwaj** [BayraktarLab/cell2location#173]
- [ ] I have confirmed this bug exists on the latest version of cell2location. See 
- [x] https://github.com/BayraktarLab/cell2location#installation
- [x] I follow the instructions from the [scvi-tools tutorial](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html).

---I followed the entire pipeline to map single cell data over spatial transcriptome data. I am trying to generate QC history plot as shown in tutorial after training with 10,000 epochs (https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html cell 19) 
But instead of getting graphical output, I am getting "2D image of my data file" 

mod.train(max_epochs=10000,
          # train using full data (batch_size=None)
          batch_size=None,
          # use all data points in training because
          # we need to estimate cell abundance at all locations
          train_size=1,
          use_gpu=True)

mod.plot_history(500)
plt.legend(labels=['full data training']);
plt.savefig('model_SP_SC_mapping_10k.png')

![image](https://user-images.githubusercontent.com/15521523/176635604-d130248b-97f4-41e3-8576-a669b1e71c6b.png)

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can run without your data, using public data)

```python
# Your code here
```

```pytb
[Paste the error output produced by the above code here]
```
Please help me to fix this issue.

**Comment by vitkl** [comment]
Hi @archanabhardwaj 

This issue is related to matplotlib rather than cell2location directly. Does this issue persist if you restart the notebook/python/terminal? 
If not - As a solution, you can use plt.show() before plotting history to make sure that the previous plot is cleared.
