### ISSUE TITLE
Extracting the spot barcodes of interested cell types after deconvolution

### ISSUE THREAD

**Issue by Zhuang-Bio** [BayraktarLab/cell2location#196]
Hi the cell2location team,

Thanks for developing this fantastic tools. I just wonder if it is possible to extract the exact barcodes of deconvoluted cell types for the downstream analysis since I would like to highlight those interesting spots using the SpatialDimPlot() function in Seurat. 

For example, here is the deconvoluted results of fibroblasts. Do you know how to extract the barcodes of colored spots?

Regarding to the deconvolution results, I use the **q05_cell_abundance_w_sf** for the following plotting, codes were shown as below.
```python
# Now we use cell2location plotter that allows showing multiple cell types in one panel
from cell2location.plt import plot_spatial

# select up to 6 clusters (can only show 6 colors)
clust_labels = ['FB-I', 'FB-II', 'FB-III', 'FB-prolif']
clust_col = ['' + str(i) for i in clust_labels] # in case column names differ from labels


with mpl.rc_context({'figure.figsize': (12, 12), 
                    'axes.grid': False}):
    fig = plot_spatial(
        adata=adata_vis_each,
        # labels to show on a plot
        color=clust_col, 
        labels=clust_labels,
        show_img=True,
        # 'fast' (white background) or 'dark_background'
        style='fast',
        # limit color scale at 99.2% quantile of cell abundance
        max_color_quantile=0.992, 
        # size of locations (adjust depending on figure size)
        circle_diameter=5,
        colorbar_position='right', # 'bottom', 'right' or None
        img_alpha=1
    )
```
![image](https://user-images.githubusercontent.com/55880584/185388082-b8caabda-0cff-4ac0-8070-6ba41d5c2d91.png)

**Comment by vitkl** [comment]
Cell2location estimates the cell abundance of those fibroblast populations in all locations. There is no way to assign a spot to one cell type. You can threshold `adata.obsm['q05_cell_abundance_w_sf'] > threshold` to assign cell types to spots but one spot will almost always have multiple cell types. If your goal is purely visualisation, then you can use the thresholding. If your goal is actually using those spots for downstream analysis, you need to rethink this, I suggest looking at https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html#Estimate-cell-type-specific-expression-of-every-gene-in-the-spatial-data-(needed-for-NCEM)
