### ISSUE TITLE
ImportError: cannot import name 'run_regression' from 'cell2location' despite setting the PYTHONNOUSERSITE param

### ISSUE THREAD

**Issue by sunnyzwu** [BayraktarLab/cell2location#208]
Hi team,

Loving the tool, which I have been using via the singularity image, but i'm now having issues installing it myself on our cluster. This seems to be a repeated issue as mentioned in  #163 but I do not seem to have any luck w/ my conda/pip environment in the run_regression step, despite including the PYTHONNOUSERSITE param prior to the building & activating the conda environment. Any recommendations? I'm using conda 4.12.0

`setenv PYTHONNOUSERSITE "literallyanyletters" `
`conda create -y -n cell2loc_env python=3.9`
`conda activate cell2loc_env`
`pip install 'git+https://github.com/BayraktarLab/cell2location.git#egg=cell2location[tutorials]'`
`python -m ipykernel install --user --name=cell2loc_env --display-name='Environment (cell2loc_env)'`
`python -c "import cell2location; from cell2location import run_regression"`

> (cell2loc_env2) [wus95@nl003 ~]$ python -c "import cell2location; from cell2location import run_regression"
Global seed set to 0
/gstore/home/wus95/miniconda3/envs/cell2loc_env2/lib/python3.9/site-packages/pytorch_lightning/utilities/warnings.py:53: LightningDeprecationWarning: pytor
ch_lightning.utilities.warnings.rank_zero_deprecation has been deprecated in v1.6 and will be removed in v1.8. Use the equivalent function from the pytorch
_lightning.utilities.rank_zero module instead.   
  new_rank_zero_deprecation(
/gstore/home/wus95/miniconda3/envs/cell2loc_env2/lib/python3.9/site-packages/pytorch_lightning/utilities/warnings.py:58: LightningDeprecationWarning: The `
pytorch_lightning.loggers.base.rank_zero_experiment` is deprecated in v1.7 and will be removed in v1.9. Please use `pytorch_lightning.loggers.logger.rank_z
ero_experiment` instead.
  return new_rank_zero_deprecation(*args, **kwargs)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'run_regression' from 'cell2location' (/gstore/home/wus95/miniconda3/envs/cell2loc_env2/lib/python3.9/site-packages/cell2lo
cation/__init__.py)

Thanks!

**Comment by vitkl** [comment]
Thanks for using cell2location, @sunnyzwu !

Please have a look at the latest cell2location tutorial, the function you are trying to use is no longer used.
