### ISSUE TITLE
plot_spatial fails with visium cytassist data

### ISSUE THREAD

**Issue by AlexanderAivazidis** [BayraktarLab/cell2location#212]
It seems like cell2location plot_spatial function does not work with new cytassist data. Cytassist includes a very large image that should not be plotted as a whole. scanpy's spatial function does the right thing:

![image](https://user-images.githubusercontent.com/46488185/203358825-459071e4-f504-4aff-92a4-d8d0d324279c.png)

But plot_spatial does not:

![image](https://user-images.githubusercontent.com/46488185/203358922-7a1c1f92-a8a9-4686-902e-60d0072a2d4f.png)

A notebook to reproduce the error is here:

https://github.com/AlexanderAivazidis/Minimum-Example/blob/main/cell2location_HumanDevelopingBrain_ctyassist.ipynb

**Comment by vitkl** [comment]
You need to crop the image using corresponding plot_spatial arguments. To do the cropping you need to decide how to do it. If you can suggest a strategy that always gives reasonable results, you can include it.

**Comment by AlexanderAivazidis** [comment]
Thanks! Working code is below:

```
from cell2location.plt import plot_spatial
clust_labels = ['Module 2', 'Module 5', 'Module 9']
clust_col = ['' + str(i) for i in clust_labels] # in case column names differ from labels
with mpl.rc_context({'figure.figsize': (15, 15)}):
    fig = plot_spatial(
        adata=slide,
        color=clust_col, labels=clust_labels,
        style='fast',
        max_color_quantile=0.992,
        circle_diameter=9,
        crop_x = [90, 965],
        crop_y = [110, 950],
        colorbar_position='right'
    )
```

![image](https://user-images.githubusercontent.com/46488185/203532061-f54390cd-1ee3-409f-b762-8c0bf9d69954.png)
