### ISSUE TITLE
How to plot images without showing the grid

### ISSUE THREAD

**Issue by brianpenghe** [BayraktarLab/cell2location#215]
Hello,

I was trying to plot cell abundance scores for one cell type.
The output image always shows the grids overlaid. Is there a way to remove it?

Thanks!
![image](https://user-images.githubusercontent.com/4110443/204113065-b446262a-69b1-4dd7-ac90-b14bbeac734b.png)

**Comment by vitkl** [comment]
This is a scanpy matplotlib settings issue. Search how to hide the grid using matplotlib.rcparam

**Comment by vitkl** [comment]
Googling finds this https://stackoverflow.com/a/50570780
