### ISSUE TITLE
error in mod.train

### ISSUE THREAD

**Issue by wanghf0501** [BayraktarLab/cell2location#225]
### Problem

I follow the instruction from https://cell2location.readthedocs.io/en/latest/, the example data works fine. However after change to  my own data, I got error at mod.train.
Script:
 mod.train(max_epochs=30000,
          # train using full data (batch_size=None)
          batch_size=None,
          # use all data points in training because
          # we need to estimate cell abundance at all locations
          train_size=1,
          use_gpu=False)

ValueError: Expected parameter rate (Tensor of shape (1, 1)) of distribution Gamma(concentration: tensor([[10.]]), rate: tensor([[nan]])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[nan]])

### Description of the data input and hyperparameters

I think the problem is my own snRNA-seq, it is a integrated (6 samples, 10X snRNA-seq) seurat object, and I convert it to the h5ad file using the following script

library(SeuratDisk)
# convert factor to character
integrated.sct@assays$RNA@data=integrated.sct@assays$RNA@counts
i <- sapply(integrated.sct@meta.data, is.factor)
integrated.sct@meta.data[i] <- lapply(integrated.sct@meta.data[i], as.character)
# set default assay
DefaultAssay(integrated.sct) <- "RNA"
SaveH5Seurat(integrated.sct, filename = "integrated.sct.h5seurat", overwrite = TRUE)
Convert("integrated.sct.h5seurat", "integrated.sct.h5ad", assay="RNA", overwrite = TRUE)
#### Single cell reference data: number of cells, number of cell types, number of genes

Thank you very much in advance!

**Comment by vitkl** [comment]
Does the error happen with cell2location or with the regression model? Your code suggests an issue with the application on the spatial rather than snRNA-seq data.

**Comment by vitkl** [comment]
I am assuming that this is resolved.
