### ISSUE TITLE
cell2location is not compatible with sklearn 1.2.0

### ISSUE THREAD

**Issue by wangjiawen2013** [BayraktarLab/cell2location#226]
Hi,
It seems that cell2location is not compatible with sklearn 1.2.0, but compatible with scikit-learn 1.0.2. When I run run_colocation with scikit-learn 1.2.0, the following error occurred (scikit-learn1.0.2 worked well):
TypeError                                 Traceback (most recent call last)
Cell In[13], line 2
      1 from cell2location import run_colocation
----> 2 res_dict, adata_vis = run_colocation(
      3     adata_vis,
      4     model_name='CoLocatedGroupsSklearnNMF',
      5     train_args={
      6       'n_fact': np.arange(11, 13), # IMPORTANT: use a wider range of the number of factors (5-30)
      7       'sample_name_col': 'sample', # columns in adata_vis.obs that identifies sample
      8       'n_restarts': 3 # number of training restarts
      9     },
     10     export_args={'path': f'{run_name}/CoLocatedComb/'}
     11 )

File ~/programs/miniconda3/envs/cellpy/lib/python3.10/site-packages/cell2location/run_colocation.py:222, in run_colocation(sp_data, n_neighbours, model_name, verbose, return_all, train_args, model_kwargs, posterior_args, export_args)
    220     print("### Training model###")
    221 if train_args["mode"] == "normal":
--> 222     mod.fit(n=train_args["n_restarts"], n_type=train_args["n_type"])
    224 elif train_args["mode"] == "tracking":
    225     raise ValueError("tracking training not implemented yet")

File ~/programs/miniconda3/envs/cellpy/lib/python3.10/site-packages/cell2location/models/downstream/CoLocatedGroupsSklearnNMF.py:169, in CoLocatedGroupsSklearnNMF.fit(self, n, n_type)
    165     self.x_data = self.X_data
    167 from sklearn.decomposition import NMF
--> 169 self.models[name] = NMF(
    170     n_components=self.n_fact,
    171     init=self.init,
    172     alpha=self.alpha,
    173     l1_ratio=self.l1_ratio,
    174     max_iter=self.n_iter,
    175     **self.nmf_kwd_args
    176 )
    177 W = self.models[name].fit_transform(self.x_data)
    178 H = self.models[name].components_

TypeError: NMF.__init__() got an unexpected keyword argument 'alpha'

**Comment by vitkl** [comment]
This was recently fixed. Please make sure you have the most up-to-date version of cell2location from GitHub:

```
conda activate cell2loc_env
pip install git+https://github.com/BayraktarLab/cell2location.git#egg=cell2location[tutorials] --upgrade
```

**Comment by vitkl** [comment]
You may need to uninstall cell2location

```
pip uninstall cell2location
pip install git+https://github.com/BayraktarLab/cell2location.git#egg=cell2location[tutorials]
```

or create a conda environment from scratch: https://github.com/BayraktarLab/cell2location#installation

**Comment by vitkl** [comment]
This should be fixed in the latest version
