### ISSUE TITLE
Error in row clustering of run_colocation clustermap

### ISSUE THREAD

**Issue by ssobt** [BayraktarLab/cell2location#272]
Hi,

I wanted to start off by saying thanks for creating a great tool for cell type co-localization. I’m eager to view the results, once I get it to work :). The issue I’ve been running into is an error in the run_colocation function, specifically the creation of the main colocation heatmap. 

The error reads:
<img width="910" alt="Screen Shot 2023-03-25 at 11 07 46 PM" src="https://user-images.githubusercontent.com/101676451/227758540-6285c905-20c0-46bf-b8bc-8ee45f938bf0.png">
<img width="910" alt="Screen Shot 2023-03-25 at 11 07 58 PM" src="https://user-images.githubusercontent.com/101676451/227758546-dbf1ca04-4bfc-436a-b2d7-d583ef7e3d30.png">

From what I can gather, the error is talking about the clustermap not being able to hierarchically cluster rows from the gene loadings (key markers). Is there a way to access the gene loadings the NMF model arrives at to see how their input into the hierarchical clustering is arriving at non finite (or missing) values? I’ve checked the posterior predictions in q05_cell_abundance_w_sf from the spatial mapping and there's no missing values there that could lead to non finite values in the gene loadings for running colocation. Is this something you’ve experienced? Any help with diagnosing the problem would be greatly appreciated!

**Comment by georgiedowsett** [comment]
Also experiencing similar problems! have you found a fix? Thank you :)

**Comment by vitkl** [comment]
This error could happen when multiple loadings have identical values for all locations/genes/cell types. Try restricting N factors to a range where such error does not happen.

**Comment by ssobt** [comment]
Apologies for the late reply, varying the range seemed to clear up the issue for me. Thanks!
