### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by stephenwilliams22** [BayraktarLab/cell2location#28]
The readme states to use `pip install plotnine pymc3>=3.8,<3.10 torch pyro-ppl` for the plotnine install but on my system 
```
$ ps -p $$
    PID TTY          TIME CMD
3713966 pts/574  00:00:00 bash
```

`pip install "plotnine pymc3>=3.8,<3.10" torch pyro-ppl` is required. you might consider updating the readme.

**Comment by vitkl** [comment]
Thanks for noting this and using our package! We recommend using the docker/singularity image where possible.
