### ISSUE TITLE
Estimated expression signature QC plot comes out splitted

### ISSUE THREAD

**Issue by jeji0209** [BayraktarLab/cell2location#282]
Hello. Thank you for the development of this excellent tool.
My estimated expression signature QC plot drawn by mod.plot_QC comes out like this.
![mod_qcplot_expr_sig_20230513](https://github.com/BayraktarLab/cell2location/assets/90094328/bf65dd96-268d-461c-8b50-94440f1242c3)
My reference scRNA-seq data consists of two batches, and they should show biological differences, as they are coming from two different regions. However, I have not seen a case where the estimated expression signature QC plot is on the diagonal line, but split into two. 
How should I interpret this result? 

Brief description of my reference scRNA-seq data. 
Batch 1: 611,034 cells, 10X chromium V3
Batch 2: 4,605 nuclei (single nucleus seq), Smartseq2

Thanks in advance :)

**Comment by vitkl** [comment]
I have never seen this before. I can recommend plotting this 2D histogram per cell type to see which cell type labels are affected by this difference.

It is possible that this has no effect on cell2location results beyond just making cell abundance estimates less comparable between cell types (eg you can’t say that cell type A is on average more abundant than cell type B - only look at the spatial distribution of both).

**Comment by jeji0209** [comment]
I checked the plot according to cell types as you recommended, and it turns out that the two lines are coming from the two seperate batches.
I believe interpreting the data as you suggested in the second sentence is the best.
Thank you :)
