### ISSUE TITLE
use of average cell types expression matrix directly from Seurat to cell2location

### ISSUE THREAD

**Issue by archanabhardwaj** [BayraktarLab/cell2location#300]
Hello 

Cell2location is really useful tool. I am using it for my spatial transcriptome (multilpe samples) dataset. Also, I have single cell data and performed all standard analysis in Seurat for the identification of multiple clusters and cell types.. Next I would like to use cell types based average expression matrix for the deconvolution analysis in cell2location.

Online manual indicates to run NB regression modeling on the raw single cell data. In order to avoid this step, I have calculated average expression per cluster in Seurat using function https://satijalab.org/seurat/reference/averageexpression and created dataframe as input for next step in cell2location. Steps follows are given below : 

# import average single cell expression matrix 

import pandas as pd                                                                                                                                                                         
import scanpy as sc
d = "avg_sc_exp"
sc = pd.read_table("avg_sc_exp", delimiter=' ')

# checked common gene labels 

intersect = np.intersect1d(adata.var_names, sc.index)
adata_vis = adata[:, intersect].copy()
sc = sc.loc[intersect, :].copy()

# create and train the model
mod = cell2location.models.Cell2location(
    adata_vis, cell_state_df=sc,
    # the expected average cell abundance: tissue-dependent
    # hyper-prior which can be estimated from paired histology:
    N_cells_per_location=10,
    # hyperparameter controlling normalisation of
    # within-experiment variation in RNA detection:
    detection_alpha=200
)
mod.view_anndata_setup()

Please let me know if I am doing something wrong while constructing average cell type expression profile. 

Thanks in advance !!!

**Comment by vitkl** [comment]
>Online manual indicates to run NB regression modeling on the raw single cell data. In order to avoid this step, I have calculated average expression per cluster in Seurat using function https://satijalab.org/seurat/reference/averageexpression and created dataframe as input for next step in cell2location. 

As far as I understand, Seurat simply computes the average RNA abundance per cell label, similarly to https://cell2location.readthedocs.io/en/latest/cell2location.cluster_averages.html. Cell2location NB regression model instead estimates average RNA abundance while accounting for technical effects in the scRNA data - which improves accuracy on a number of datasets we used (see supplementary figures about lymph nodes).

**Comment by archanabhardwaj** [comment]
Thanks alot for your suggestion.  I totally agree with you. Therefore, I am doing NB regression model to include the technical effects for high accuracy while calculating the average RNA abundance.
