### ISSUE TITLE
AttributeError: 'Cell2location' object has no attribute 'samples'

### ISSUE THREAD

**Issue by hkeremcil** [BayraktarLab/cell2location#302]
In the tutorials notebook, I came all the way to the "Estimate cell-type specific expression of every gene in the spatial data (needed for NCEM)" part without any problems. All the outputs look perfect. But I encountered that error in the title while running this code:
```
# Compute expected expression per cell type
expected_dict = mod.module.model.compute_expected_per_cell_type(
    mod.samples["post_sample_q05"], mod.adata_manager
)

# Add to anndata layers
for i, n in enumerate(mod.factor_names_):
    adata_vis.layers[n] = expected_dict['mu'][i]

# Save anndata object with results
adata_file = f"{run_name}/sp.h5ad"
adata_vis.write(adata_file)
adata_file
```
It doesn't like this line: mod.samples["post_sample_q05"], mod.adata_manager

Do you know what could cause this? I would highly appreciate any help on this issue. 

And another quick question: Can I run this part on Google Colab Pro, or do I need Google Colab Pro Plus considering the amount of RAM it requires (I have big data of RNAseq reference data combined for several samples and also 4 different slides in adata_vis)?

Many thanks in advance!

**Comment by vitkl** [comment]
`mod.samples` issue has been explained previously here https://github.com/BayraktarLab/cell2location/issues/143#issuecomment-1098245626

> And another quick question: Can I run this part on Google Colab Pro, or do I need Google Colab Pro Plus considering the amount of RAM it requires (I have big data of RNAseq reference data combined for several samples and also 4 different slides in adata_vis)?

I don't know. This set indeed requires a lot of RAM and these is not much that can be done to address this. This step does not require using the GPU - so you can use any computational resource to analyse it - maybe your institute HPC has better options.

**Comment by hkeremcil** [comment]
> `mod.samples` issue has been explained previously here [#143 (comment)]

I followed this and it worked. Many thanks!
