### ISSUE TITLE
Problem importing cell2location after setting THEANO_FLAGS

### ISSUE THREAD

**Issue by galanisl** [BayraktarLab/cell2location#31]
Hi, I'm trying to run cell2location from the singularity image (`cell2location-v0.05-alpha.sif`) but I'm getting the following error:

```
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

This is what I'm trying to do:

```
import os
os.environ["THEANO_FLAGS"] = 'device=cuda0,floatX=float32,force_device=True'
import cell2location
```

If I change the above to:

```
import os
os.environ["THEANO_FLAGS"] = 'device=cpu,floatX=float32,openmp=True,force_device=True'
import cell2location
```

`cell2location` is successfully imported but I would like to take advantage of GPU acceleration.

Thanks in advance!

**Comment by Chuang1118** [comment]
Hello,
I have the same problem with submitting a cluster job (Slurm system) with GPU.
Step one(run_regression) works fine for me.

**Comment by vitkl** [comment]
Hi @galanisl 

Thanks for using cell2location. Step 1 should indeed work without theano, but you would indeed benefit from GPU acceleration for step 2. 

This is unusual error and we have not tested the image on Slurm clusters. Can you please post the command you use to start the container? 
It is important to use `--no-home` option to ensure that singularity does not load your jupyter kernels from the home directory and well as use environmental variables from your home directory - which can hide necessary Nvidia drivers from inside the container.

**Comment by galanisl** [comment]
Hi @vitkl 

Thanks for the prompt reply. These are the series of steps I'm trying in SLURM:

```
# Allocate resources for the cell2location pipeline
srun --partition=gpu --x11 --gres=gpu:GTX-1080:2 --mem=60000M --time=10:00:00 --pty bash

# Launch Jupyter from within the Singularity image
singularity exec \
   --no-home  \
   --nv \
   -B /working_dir:/cell2loc \
   /path/to/image/cell2location-v0.05-alpha.sif \
   /bin/bash -c "cd /cell2loc && HOME=$(mktemp -d) jupyter notebook \
      --notebook-dir=/cell2loc --NotebookApp.token='cell2loc' \
      --ip=0.0.0.0 --port=1237 --no-browser --allow-root"
```

Also, for your interest, I get the same error I mentioned above even if I try to call `cell2location.run_cell2location` in CPU mode, i.e. if I use the following THEANO_FLAGS:

```
os.environ["THEANO_FLAGS"] = 'device=cpu,floatX=float32,openmp=True,force_device=True'
```

**Comment by Chuang1118** [comment]
hi,

Wow, galanisl, you can use the interactive mode jupyter cool :100:  

I have the same error message "ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory",
but I can import cell2location.

```
data_type = 'float32'
os.environ["THEANO_FLAGS"] = 'device=cuda,floatX=' + data_type + ',force_device=True'
import cell2location
cell2location.run_cell2location
```
<function cell2location.run_c2l.run_cell2location(sc_data, sp_data, model_name=None, verbose=True, show_locations=False, return_all=True, summ_sc_data_args={'cluster_col': 'annotation_1'}, train_args={'n_iter': 20000, 'learning_rate': 0.005, 'sample_prior': False, 'readable_var_name_col': None, 'sample_name_col': None}, model_kwargs={}, posterior_args={'n_samples': 1000}, export_args={'path': './results', 'save_model': False, 'run_name_suffix': '', 'scanpy_coords_name': 'coords'})>

I got error message when I have executed 
```
r = cell2location.run_cell2location(
                      sc_data=adata_snrna_raw  or inf_aver, 
                      sp_data=adata_vis, ....)
```
adata_snrna_raw : output step 1
inf_aver : dataframe 24001 rows × 21 columns
adata_vis : AnnData
adata_vis.raw.X : <class 'numpy.float32'>

code submit on Slurm
```
#!/bin/sh

#SBATCH -J c2l
#SBATCH -A b098
#SBATCH --nodes=1
#SBATCH --mem=80G
#SBATCH -t 01:30:00
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=dong@ciml.univ-mrs.fr
#SBATCH -p gpu 
#SBATCH --gres=gpu:2


module load userspace/all
module load singularity/3.5.1
module load pgi64/2018
module load cuda
module load cuda-drivers

hostname

singularity exec \
        --nv \
        --no-home  \
        -B /scratch/cdong:/scratch/cdong ./simg/cell2location-v0.05-alpha.sif \
        /bin/bash -c "HOME=$(mktemp -d) jupyter nbconvert --to notebook --execute ./notebooks/analysis_1_spatial_mapping.ipynb --output=/scratch/cdong/cell2loc/fl/notebooks/out_3.ipynb"
```

I don't think so I can use the interactive mode jupyter, I am not sure HPC has visualization node over 50G.

**Comment by vitkl** [comment]
Thanks for clarifying the details. I can try to test the container in the Slurm environment next week but I did not use Slurm for a while and not sure if I still have access. Is contacting your local IT an option? This error might be specific to Slurm in some way because we do not see it when using Singularity on LSF cluster and when using Docker image locally and on the cloud.

Martin @prete helped us build the image - I am wondering if this error rings a bell to you? 

@Chuang1118 when analysing sample-by sample 40GB of RAM should suffice - in case this helps.

**Comment by vitkl** [comment]
@Chuang1118 seems to have found the solution by modifying slurm parameters https://github.com/BayraktarLab/cell2location/discussions/30#discussioncomment-517259
