### ISSUE TITLE
ValueError: You selected `Trainer(strategy='ddp_fork')` but process forking is not supported on this platform. We recommed `Trainer(strategy='ddp_spawn')` instead.

### ISSUE THREAD

**Issue by realzehuali** [BayraktarLab/cell2location#319]
I was following exactly the same tutorial notebook and met this error when running this block:
mod.train(max_epochs=30000, 
          # train using full data (batch_size=None)
          batch_size=None, 
          # use all data points in training because 
          # we need to estimate cell abundance at all locations
          train_size=1,
          use_gpu=True,
         )

# plot ELBO loss history during training, removing first 100 epochs from the plot
mod.plot_history(1000)
plt.legend(labels=['full data training']);

The error message is: 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[36], line 1
----> 1 mod.train(max_epochs=30000, 
      2           # train using full data (batch_size=None)
      3           batch_size=None, 
      4           # use all data points in training because 
      5           # we need to estimate cell abundance at all locations
      6           train_size=1,
      7           use_gpu=True,
      8          )
     10 # plot ELBO loss history during training, removing first 100 epochs from the plot
     11 mod.plot_history(1000)

File ~\anaconda3\envs\cell2loc_env\lib\site-packages\cell2location\models\_cell2location_model.py:209, in Cell2location.train(self, max_epochs, batch_size, train_size, lr, num_particles, scale_elbo, **kwargs)
    206         scale_elbo = 1.0 / (self.summary_stats["n_cells"] * self.summary_stats["n_vars"])
    207     kwargs["plan_kwargs"]["scale_elbo"] = scale_elbo
--> 209 super().train(**kwargs)

File ~\anaconda3\envs\cell2loc_env\lib\site-packages\scvi\model\base\_pyromixin.py:145, in PyroSviTrainMixin.train(self, max_epochs, use_gpu, accelerator, device, train_size, validation_size, shuffle_set_split, batch_size, early_stopping, lr, training_plan, plan_kwargs, **trainer_kwargs)
    141     plan_kwargs.update({"optim_kwargs": {"lr": lr}})
    143 if batch_size is None:
    144     # use data splitter which moves data to GPU once
--> 145     data_splitter = DeviceBackedDataSplitter(
    146         self.adata_manager,
    147         train_size=train_size,
    148         validation_size=validation_size,
    149         batch_size=batch_size,
    150         accelerator=accelerator,
    151         device=device,
    152     )
    153 else:
    154     data_splitter = self._data_splitter_cls(
    155         self.adata_manager,
    156         train_size=train_size,
   (...)
    159         batch_size=batch_size,
    160     )

File ~\anaconda3\envs\cell2loc_env\lib\site-packages\scvi\dataloaders\_data_splitting.py:414, in DeviceBackedDataSplitter.__init__(self, adata_manager, train_size, validation_size, accelerator, device, pin_memory, shuffle, shuffle_test_val, batch_size, **kwargs)
    412 self.shuffle = shuffle
    413 self.shuffle_test_val = shuffle_test_val
--> 414 _, _, self.device = parse_device_args(
    415     accelerator=accelerator, devices=device, return_device="torch"
    416 )

File ~\anaconda3\envs\cell2loc_env\lib\site-packages\scvi\model\_utils.py:103, in parse_device_args(use_gpu, accelerator, devices, return_device, validate_single_device)
    100 if _validate_single_device and (cond1 or cond2 or cond3):
    101     raise ValueError("Only a single device can be specified for `device`.")
--> 103 connector = _AcceleratorConnector(accelerator=accelerator, devices=devices)
    104 _accelerator = connector._accelerator_flag
    105 _devices = connector._devices_flag

File ~\anaconda3\envs\cell2loc_env\lib\site-packages\lightning\pytorch\trainer\connectors\accelerator_connector.py:166, in _AcceleratorConnector.__init__(self, devices, num_nodes, accelerator, strategy, plugins, precision, sync_batchnorm, benchmark, use_distributed_sampler, deterministic)
    164     self._strategy_flag = self._choose_strategy()
    165 # In specific cases, ignore user selection and fall back to a different strategy
--> 166 self._check_strategy_and_fallback()
    167 self._init_strategy()
    169 # 5. Instantiate Precision Plugin

File ~\anaconda3\envs\cell2loc_env\lib\site-packages\lightning\pytorch\trainer\connectors\accelerator_connector.py:457, in _AcceleratorConnector._check_strategy_and_fallback(self)
    453     raise MisconfigurationException(
    454         f"You selected strategy to be `{FSDPStrategy.strategy_name}`, but GPU accelerator is not used."
    455     )
    456 if strategy_flag in _DDP_FORK_ALIASES and "fork" not in torch.multiprocessing.get_all_start_methods():
--> 457     raise ValueError(
    458         f"You selected `Trainer(strategy='{strategy_flag}')` but process forking is not supported on this"
    459         f" platform. We recommed `Trainer(strategy='ddp_spawn')` instead."
    460     )
    461 if strategy_flag:
    462     self._strategy_flag = strategy_flag

ValueError: You selected `Trainer(strategy='ddp_fork')` but process forking is not supported on this platform. We recommed `Trainer(strategy='ddp_spawn')` instead.

I was using the lastest version of scvi and cell2location. I have 2 3090 GPUs.
Thank you for any help!

**Comment by vitkl** [comment]
You should be using only one GPU. 

How do you initial training? Please post the exact code.

If using multi-GPU is the current lightning default when the device has >1 GPU - this would require a different default of almost all scvi-tools models, right @adamgayoso @martinkim0?

**Comment by realzehuali** [comment]
I was following exactly the same code in the tutorial notebook

**Comment by martinkim0** [comment]
@vitkl Correct, not sure why this is occurring since our default only chooses a single device. 

@realzehuali Could you try passing in `accelerator="gpu"` and `devices=[0,1]` instead of `use_gpu`(which is a deprecated argument)?

**Comment by vitkl** [comment]
Thanks @martinkim0!

Does this solution work for you @realzehuali? Maybe try installing latest `scvi-tools` and latest cell2location from GitHub (`pip install git+https://github.com/BayraktarLab/cell2location.git#egg=cell2location[tutorials]`) into a clean conda environment?

**Comment by vitkl** [comment]
Did this resolve itself?

**Comment by zehualilab** [comment]
Sorry for my late reply. It worked well with your suggestions! Thanks a lot!
