### ISSUE TITLE
Bug related to top_n in run_colocation

### ISSUE THREAD

**Issue by menelson** [BayraktarLab/cell2location#32]
Hi guys,

Thanks for this nice package and very helpful tutorial. In run_colocation.py you save the top 10 ranking cell types for each factor to a dataframe using print_gene_loadings on L245:

https://github.com/BayraktarLab/cell2location/blob/master/cell2location/run_colocation.py#L245

This leads to an error when returning the dataframe whenever the user has fewer than 10 cell types because I see that the top_n variable is set to 10 by default in the source of print_gene_loadings:

https://cell2location.readthedocs.io/en/latest/_modules/cell2location/models/base_model.html#BaseModel.print_gene_loadings

Can I suggest that you add a parameter for top_n when run_colocation is called, so that top_n can only take integer values up to the total number of annotations being mapped with cell2location, and then call this top_n value at L245 in run_colocation.py.

Cheers!

**Comment by menelson** [comment]
Further to my previous point I have my own version run_location.py with the fix. Happy to push this myself or indeed put the changes in a separate branch and submit a merge request for you to review, just let me know.

**Comment by vitkl** [comment]
Hi @menelson 

Thanks for using cell2location and for these suggestions. Can you please fork cell2location, create a separate branch with the changes, do a pull request?

**Comment by menelson** [comment]
Hi @vitkl apologies for the delay, pull request from my fork now submitted!

**Comment by vitkl** [comment]
Thanks for contributing :)

**Comment by wangjiawen2013** [comment]
Hi,
run_colocation uses all the available CPU of my server, how to limit the CPU number ? Or can we use GPU instead ?

**Comment by vitkl** [comment]
It's not possible to use GPU for this step. Under the hood we are using sklearn NMF - please check how to restrict cpu use for that package.
