### ISSUE TITLE
run_colocation NMF bug

### ISSUE THREAD

**Issue by Famingzhao** [BayraktarLab/cell2location#340]
- [x] I have confirmed this bug exists on the latest version of cell2location. See https://github.com/BayraktarLab/cell2location#installation
- [x] I follow the instructions from the [scvi-tools tutorial](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html).

### Minimal code sample (that we can run without your data, using public data)

```python
from cell2location import run_colocation
res_dict, adata_st = run_colocation(
    adata_st,
    model_name='CoLocatedGroupsSklearnNMF',
    train_args={
      'n_fact': np.arange(11, 13), # IMPORTANT: use a wider range of the number of factors (5-30)
      'sample_name_col': 'orig.ident', # columns in adata_vis.obs that identifies sample
      'n_restarts': 3 # number of training restarts
    },
    # the hyperparameters of NMF can be also adjusted:
    model_kwargs={'alpha': 0.01, 'init': 'random', "nmf_kwd_args": {"tol": 0.000001}},
    export_args={'path': './CoLocatedComb/'}
)
```

```pytb
### Analysis name: CoLocatedGroupsSklearnNMF_11combinations_1075locations_15factors
/data_disk/ST01/DJT/User/zhaoxm/miniconda3/envs/cell2loc/lib/python3.9/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
/data_disk/ST01/DJT/User/zhaoxm/miniconda3/envs/cell2loc/lib/python3.9/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
/data_disk/ST01/DJT/User/zhaoxm/miniconda3/envs/cell2loc/lib/python3.9/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
/data_disk/ST01/DJT/User/zhaoxm/miniconda3/envs/cell2loc/lib/python3.9/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
Some error in plotting with scanpy or `cell2location.plt.plot_factor_spatial()`
 index 0 is out of bounds for axis 0 with size 0
### Analysis name: CoLocatedGroupsSklearnNMF_12combinations_1075locations_15factors
Some error in plotting with scanpy or `cell2location.plt.plot_factor_spatial()`
 index 0 is out of bounds for axis 0 with size 0
```

**Comment by colin-leeyc** [comment]
I am encountering the same bug!

**Comment by vitkl** [comment]
This just means that `cell2location.plt.plot_factor_spatial()` failed with error `index 0 is out of bounds for axis 0 with size 0`. This could be a package version mismatch or that for this data NMF arrived at one or many factors which have 0 value for all locations. You would be missing the corresponding spatial plots.

**Comment by Famingzhao** [comment]
> This just means that `cell2location.plt.plot_factor_spatial()` failed with error `index 0 is out of bounds for axis 0 with size 0`. This could be a package version mismatch or that for this data NMF arrived at one or many factors which have 0 value for all locations. You would be missing the corresponding spatial plots for 11 and 12 factors.

Thanks for the reminder!
