### ISSUE TITLE
Question: cell proportion, cell abundance and spatial clustering

### ISSUE THREAD

**Issue by dyinboisry4u** [BayraktarLab/cell2location#342]
Hi, @vitkl, thanks to develop a great tool, it helps me a lot, I have several questions about c2l downstream analysis:
1. In c2l tutorial, we use `cell abundance` estimated by c2l as downstream clustering input. And you suggest `Normalising to the total per spot doesn't simplify comparisons of cell abundance between cell types in any way.` (https://github.com/BayraktarLab/cell2location/issues/151#issuecomment-1140102241). But in some research(`https://doi.org/10.1038/s41586-022-05060-x`), I noticed the author use c2l `cell proportion` with performing isometric log ratios transformation (https://github.com/saezlab/visium_heart/issues/7#issuecomment-1257764447) as clustering input. I'm really confused if I can use `cell proportion per spot` for downstream analysis.
2. Could I use some spatial clustering methods to detect spatial domains, and then assign c2l `cell abundance` for each domains to illustrate the cell composition of each domain(something like `domain - cell abundance` dotplot)?

**Comment by dyinboisry4u** [comment]
I got it in c2l paper

**Comment by whitneyt1** [comment]
hi @dyinboisry4u, i am wondering why you closed this question and was wondering if you had and answers to your above questions? 

thanks!
