### ISSUE TITLE
Using a single cell RNA-seq dataset to deconvolute a bulk RNA-seq data

### ISSUE THREAD

**Issue by lihaowhusos** [BayraktarLab/cell2location#349]
I have annotationed single cell RNA-seq data and bulk RNA-seq data and want to deconvolute the  bulk RNA-seq with the single cell RNA-seq. Is this appropriate with cell2location method?

**Comment by vitkl** [comment]
You could certainly attempt this, provided you have a way to evaluate which methods produce better bulk deconvolution.

One caveat is that you cannot use a cell number prior realistic for bulk data (which would be 10k-mlns of cells) - you need to use numbers in roughly in range 1-100.

**Comment by lihaowhusos** [comment]
Thanks so much for your response! I have try it and the results are generally in line with expectations.

**Comment by lihaowhusos** [comment]
> You could certainly attempt this, provided you have a way to evaluate which methods produce better bulk deconvolution.
> 
> One caveat is that you cannot use a cell number prior realistic for bulk data (which would be 10k-mlns of cells) - you need to use numbers in roughly in the range 1-100.

Thanks so much for your response! I have try it and the results are generally in line with expectations.
