### ISSUE TITLE
Is it possible to run cell2location in local computers?

### ISSUE THREAD

**Issue by hkeremcil** [BayraktarLab/cell2location#353]
Me and my colleagues were only able to successfully set up the environment and run the entire cell2location pipeline in Google Colab. The tutorial in the documentation is only for Google Colab as well. Is it currently possible to run it locally? If so, can I get some guidance on how to do that? Is there a separate tutorial for local usage?

Many thanks in advance!

**Comment by vitkl** [comment]
The installation instructions in the readme page on GitHub https://github.com/BayraktarLab/cell2location?tab=readme-ov-file#installation would allow you to install and use the package. Only the first cell in this tutorial https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html is different between Colab and normal use.

**Comment by hkeremcil** [comment]
I haven't realized that the rest of the tutorial is the same for Colab and local use. This is very good to know, thank you.
