### ISSUE TITLE
Error from import cell2location

### ISSUE THREAD

**Issue by camerongw** [BayraktarLab/cell2location#37]
Hi, I was just wondering whether anyone could interpret this error or give me any tips how to fix it? I've installed cell2location in a conda environment as per the instructions to do so manually but am getting this error upon trying to import it:

```python
In [1]: import sys
   ...: import scanpy as sc
   ...: import anndata
   ...: import pandas as pd
   ...: import numpy as np
   ...: import os
   ...:
   ...: data_type = 'float32'
   ...:
   ...: import cell2location
   ...:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Storing i64 to ptr of i32 ('dim'). FE type int32

File "../../../.local/lib/python3.7/site-packages/umap/layouts.py", line 52:
def rdist(x, y):
    <source elided>
    result = 0.0
    dim = x.shape[0]
    ^

During: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at /home/camerongw/.local/lib/python3.7/site-packages/umap/layouts.py (52)
```

I'm using python-3.7.10.

**Comment by yozhikoff** [comment]
Hi camerongw!

I can't reproduce this error, but it's definitely something related to the `numba` package. Are you using the `0.53.0` version?
Could you please try the following?

`conda update numba`

**Comment by yozhikoff** [comment]
@vitkl I also got some errors when tested the manual installation, e.g. I had to reinstall `arviz` because the initial version was incompatible with our `pymc3` version.
I guess we'll have to do something with it at some point.

**Comment by vitkl** [comment]
Are you using the `environment.ylm` file?

**Comment by vitkl** [comment]
Otherwise, yes, we need to test the model with latest pymc3 version.

**Comment by yozhikoff** [comment]
> Are you using the `environment.ylm` file?

No, I mean the fully manual installation. 

> Otherwise, yes, we need to test the model with latest pymc3 version.

And add automated tests like those in `SCVI`.

**Comment by vitkl** [comment]
@camerongw Did you create conda environment using ylm file? It might help to use the ylm file which fixes compatible version or to use our singularity/docker images: https://github.com/BayraktarLab/cell2location#using-singularity-image

**Comment by vitkl** [comment]
I would strongly recommend using a separate conda environment for cell2location and other tools you are using. 

If you are already doing that your error suggests that python uses `umap` from `.local/lib/python3.7/site-packages/umap`  rather than conda environment. This is a common error in some HPC and can be solved by disabling the pip user site by adding this line to your `.bashrc`:
```
export PYTHONNOUSERSITE="canbeanyletters"
```
You also need to make sure that you active the conda environment, and that your `$PATH` environmental variable contains path to the conda environment before the path to any other python installation.
