### ISSUE TITLE
Regarding the reliability of the single-cell sequencing reconstruction plot, how should the N_cells_per_location and detection_alpha parameters be set?

### ISSUE THREAD

**Issue by guo8139** [BayraktarLab/cell2location#394]
I would like to express my sincere thanks to the authors for developing this incredibly useful software package. Their work has made a significant impact on the field, and I truly appreciate the effort and innovation that went into creating this tool. However, when I follow the official guidelines to run the code, I encounter the following confusions:
Question 1: When processing a single-cell reference dataset, are my quality control results reliable? How can I adjust the parameters to make the plot(Fig2) more closely match the diagonal?

selected = filter_genes(adata_ref, cell_count_cutoff=5, cell_percentage_cutoff2=0.05, nonz_mean_cutoff=1.15)
Fig1
![image](https://github.com/user-attachments/assets/c8447f70-2960-4249-9ee3-b864ac0983a6)
Fig2
![image](https://github.com/user-attachments/assets/855d86e9-773f-49b4-8088-ebf13ff43ea7)

Question 2: When processing multiple spatial transcriptomics datasets, can I run them slice by slice? Due to limitations in the physical machine's performance, I execute the following code on one slice, and it takes about 1-2 hours. However, when running 10 slices simultaneously, it takes about 7-10 days. All 10 slices are from the same batch.

mod.train(max_epochs=30000,
          # train using full data (batch_size=None)
          batch_size=None,
          # use all data points in training because we need to estimate cell abundance at all locations
          train_size=1
         )

Another reason I process individual samples one by one is that I noticed in the 10 slices, some slices have a significantly different N_cells_per_location parameter compared to the others (most slices have N_cells_per_location = 3). In addition, should I remove spots with very low RNA content? My specimen is an atherosclerotic plaque, and it contains large areas of necrotic tissue with very few cells (most spots have no cells, and only a few contain 1-2 cells). However, from the results（Fig3/4）, it seems that cell2location has identified these low-quality spots. Additionally, I would like to know, based on Figures 3 and 4, whether it's better to choose detection_alpha = 20 or detection_alpha = 200. Can low-quality spots also be considered a type of technical effect?
Fig3，detection_alpha=20
![image](https://github.com/user-attachments/assets/025f4bd5-01c4-4fd9-929e-894b68071665)
Fig4，detection_alpha=200
![image](https://github.com/user-attachments/assets/8157ad09-c293-4c55-b521-d9cb1c997d8d)

**Comment by vitkl** [comment]
In which case does cell abundance better match cell numbers seen in the underlying histology images? That helps select appropriate hyperparameters.
