### ISSUE TITLE
Google colab tutorial gives error on 'import cell2location'

### ISSUE THREAD

**Issue by narein97** [BayraktarLab/cell2location#42]
The colab [tutorial](https://colab.research.google.com/github/BayraktarLab/cell2location/blob/master/docs/notebooks/cell2location_short_demo_colab.ipynb) given on the cell2location documentation page gives an error when trying to import cell2location at cell 3, line 15. (DistributionNotFound: The 'pynndescent' distribution was not found and is required by the application). Is there anyway to resolve this ?

**Comment by vitkl** [comment]
Thanks for submitting the issue. I will look into that. 

Reproducing software environment on Google Colab gets harder with time so I would recommend using our singularity/docker images or conda installation on your local machine or dedicated cloud solution for analysing your data.

**Comment by vitkl** [comment]
I am also getting this error with the `vitkl/cell2location_numpyro` repo. @yozhikoff do you have any idea what it means?
<img width="1272" alt="Screenshot 2021-04-11 at 13 47 35" src="https://user-images.githubusercontent.com/22567383/114304731-ab20ee00-9acc-11eb-894b-2cb404df204f.png">

**Comment by narein97** [comment]
@vitkl For the moment I was able to handle the error by running the following (assume that I've already downloaded setup_collab.sh)

`!pip install pynndescent`
`!pip install git+https://github.com/theislab/scanpy.git@1.7.0rc1`
`!bash setup_collab.sh`
 
Hope this helps

**Comment by yozhikoff** [comment]
Thanks @narein97 !
I will update `setup_collab.sh` to include these lines as a temporary workaround until we find a better solution

**Comment by vitkl** [comment]
This solution does not work for me (cannot find scanpy on import). Probably Colab changed default package versions or how they are imported.

**Comment by narein97** [comment]
@vitkl I faced the same issue. What solved it for me was factory resetting the runtime and running it again.

**Comment by TaoYang-dev** [comment]
For those who are still struggling on using GPU in Colab, I managed to set it up and run correctly by the code below. Hope it helps.

! pip install pynndescent
! pip install git+https://github.com/theislab/scanpy.git@1.7.0rc1
! pip install pyro-ppl
! wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
! chmod +x Miniconda3-latest-Linux-x86_64.sh
! bash ./Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local
! conda install -q -y --prefix /usr/local python=3.7 numpy pandas jupyter leidenalg python-igraph louvain hyperopt loompy cmake nose tornado dill ipython bbknn seaborn matplotlib request mkl-service pygpu theano --channel bioconda --channel conda-forge
! pip install -q --prefix /usr/local plotnine pymc3
! git clone https://github.com/BayraktarLab/cell2location.git cell2location_repo
! cd cell2location_repo && pip install -q --prefix /usr/local .
