### ISSUE TITLE
Tutorial not running on Docker version

### ISSUE THREAD

**Issue by FPetitprez** [BayraktarLab/cell2location#44]
Hello,
Congratulations for this tools, which seems impressive! I would like to run it on my data, so I installed the docker image. Before running it on my data, I wanted to try the tutorial. So i opened the "cell2location_estimating_signatures" jupyter notebook, and tried to run it.  From the second block of code (Loading single-cell reference data), I have a file not found error :

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-9e8820da3986> in <module>
      3 
      4 ## snRNA reference (raw counts)
----> 5 adata_snrna_raw = anndata.read_h5ad(sc_data_folder + "rawdata/all_cells_20200625.h5ad")
      6 
      7 ## Cell type annotations

/opt/conda/envs/cellpymc/lib/python3.7/site-packages/anndata/_io/h5ad.py in read_h5ad(filename, backed, as_sparse, as_sparse_fmt, chunk_size)
    398     )
    399 
--> 400     with h5py.File(filename, "r") as f:
    401         d = {}
    402         for k in f.keys():

/opt/conda/envs/cellpymc/lib/python3.7/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    406                 fid = make_fid(name, mode, userblock_size,
    407                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 408                                swmr=swmr)
    409 
    410             if isinstance(libver, tuple):

/opt/conda/envs/cellpymc/lib/python3.7/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = '/sanger_projects/cell2location_paper/notebooks/selected_data/mouse_visium_snrna/rawdata/all_cells_20200625.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I also tried to download the files using the link in the preprint and change the path to the local path on my computer, with the same result.
I am new to docker images, so I am not sure whether the path is related to an online location or locally.

Is there an easy fix for this, or should I try to use another way of accessing cell2location than the docker image?

Thank you in advance.

Best regards,
Florent

**Comment by yozhikoff** [comment]
Hello @FPetitprez !
Docker is an isolated execution environment, so by default it doesn't have access to your local files.
You first need to mount your local directory to your docker container 
```
docker run -v /host/directory:/container/directory
```

In our particular case
```
docker run -v  /host/directory:/container/directory -i --rm -p 8848:8888 --gpus all quay.io/vitkl/cell2location:latest
```

**Comment by FPetitprez** [comment]
Thank you very much for this explanation! I could load the data properly and I arrived to the step 4 of the first part of the tutorial.
I first encourntered an error about unsufficient shared memory, that I fixed by running the docker image with option --ipc=host.
But now I have another memory issue with CUDA:
RuntimeError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 3.82 GiB total capacity; 1.99 GiB already allocated; 167.88 MiB free; 2.17 GiB reserved in total by PyTorch)
Do you know how this could be fixed?

**Comment by yozhikoff** [comment]
That's because your data is too large to fit into your GPU.
I'm afraid there are only a few options and all of them are far from perfect. You can
 - find a GPU with more memory
 - try to run cell2location on CPU, although it will likely require a couple of days

**Comment by FPetitprez** [comment]
Ok, I guess I will try on CPU only with more patience. Thank you for the assistance !

**Comment by FPetitprez** [comment]
I tried running it without hte GPUs, and at the same step, I have an error saying I need to run it on the GPU as well:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-d02d8021d325> in <module>
     30                    export_args={'path': results_folder + 'regression_model/', # where to save results
     31                                 'save_model': True, # save pytorch model?
---> 32                                 'run_name_suffix': ''})
     33 
     34 reg_mod = r['mod']

/opt/conda/envs/cellpymc/lib/python3.7/site-packages/cell2location/run_regression.py in run_regression(sc_data, model_name, verbose, return_all, train_args, model_kwargs, posterior_args, export_args)
    170                 use_average_as_initial_value=train_args['use_average_as_initial_value'],
    171                 verbose=False,
--> 172                 **model_kwargs)
    173 
    174     ####### Print run name #######

/opt/conda/envs/cellpymc/lib/python3.7/site-packages/cell2location/models/RegressionGeneBackgroundCoverageTorch.py in __init__(self, sample_id, cell2covar, X_data, data_type, n_iter, learning_rate, total_grad_norm_constraint, verbose, var_names, var_names_read, obs_names, fact_names, minibatch_size, minibatch_seed, prior_eps, nb_param_conversion_eps, use_cuda, use_average_as_initial_value, stratify_cv)
    201                                                             self.n_fact, self.clust_average_mat,
    202                                                             which_sample=self.which_sample,
--> 203                                                             data_type=self.data_type)
    204 
    205     # =====================DATA likelihood loss function======================= #

/opt/conda/envs/cellpymc/lib/python3.7/site-packages/cell2location/models/RegressionGeneBackgroundCoverageTorch.py in __init__(self, n_cells, n_genes, n_fact, clust_average_mat, which_sample, data_type, eps)
     79 
     80         # ====================Covariate and sample effects======================= #
---> 81         self.gene_factors_log = nn.Parameter(torch.Tensor(self.n_fact, self.n_genes))
     82 
     83         # =====================Sample-specific scaling of expression levels ======================= #

/opt/conda/envs/cellpymc/lib/python3.7/site-packages/torch/cuda/__init__.py in _lazy_init()
    170         # This function throws if there's a driver initialization error, no GPUs
    171         # are found or any other error occurs
--> 172         torch._C._cuda_init()
    173         # Some of the queued calls may reentrantly call _lazy_init();
    174         # we need to just return without initializing in that case.

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

I guess I will have to try on another computer then. Thank you anyway.

**Comment by yozhikoff** [comment]
Have you specified the `'use_cuda': False` option in the `run_regression` function?

**Comment by FPetitprez** [comment]
I had not, and this fixes my issue. Thank you!

**Comment by vitkl** [comment]
`run_regression` is quite fast without the GPU as well but the main spatial mapping model (second tutorial notebook) is indeed much slower (days). How large is your spatial data? If it is less than 2500 locations * 12k genes, 3.82 GiB of GPU memory could be enough. I would at least give it a try.

**Comment by vitkl** [comment]
In the first notebook, you can also try increasing the train_proportion to
keep just 1-2k cells for validation. This would mean less data is loaded on
a GPU. What is your current total number of cells and train_proportion?
