### ISSUE TITLE
Issue while saving regression result

### ISSUE THREAD

**Issue by simoncmo** [BayraktarLab/cell2location#45]
Hi, I was running regression on my training data, and after it's done. the saving failed half way through..
```
### Evaluating parameters / sampling posterior ### - time 212.25 min
### Saving results ###
... storing 'sample_id' as categorical
... <And other storing stuff>

Traceback (most recent call last):
  File "/anaconda3/envs/cellpymc/lib/python3.7/site-packages/anndata/_io/utils.py", line 188, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/anaconda3/envs/cellpymc/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 254, in write_dataframe
    raise ValueError(f"{reserved!r} is a reserved name for dataframe columns.")
ValueError: '_index' is a reserved name for dataframe columns.
The above exception was the direct cause of the following exception:
```
The read the sc.h5ad file. It only has its raw matrix X. All the other meta (obs, var, uns) are empty. let along the model..
I used Python script to run it so all is lost..
Is there a way to somehow save the result without running into this issue?

**Comment by vitkl** [comment]
Hi @simoncmo 

Thanks for using our package! This looks like anndata issue to me. You need to check that you can save the anndata object (`adata.write(file_name)`) before running `cell2location.run_regression()` and solve any saving issues if they arise. Does this solve your issue?
It can also be a good idea to check that the workflow can finish successfully in a python script by doing very short training (e.g 1 epoch).
