### ISSUE TITLE
adding Nanostring WTA notebook to docs

### ISSUE THREAD

**Issue by vitkl** [BayraktarLab/cell2location#46]
Hi @AlexanderAivazidis 

Could I ask you to add code that visualises cell abundance along 1D axis (line plot + dotplot) to the notebook?
https://github.com/BayraktarLab/cell2location/blob/master/docs/notebooks/cell2loation_for_NanostringWTA.ipynb

And this is a reminder for me to add the links to docs website.

**Comment by AlexanderAivazidis** [comment]
I added the dotplot for absolute abundances now

**Comment by vitkl** [comment]
@AlexanderAivazidis  Please also update model math to NB (from Poisson)
https://github.com/BayraktarLab/cell2location/blob/master/cell2location/models/LocationModelWTA.py

**Comment by vitkl** [comment]
Hi @AlexanderAivazidis gentle reminder to update

**Comment by vitkl** [comment]
@AlexanderAivazidis is the description of WTA model correct?

**Comment by AlexanderAivazidis** [comment]
Yes I have corrected this now.

**Comment by vitkl** [comment]
Not quite, NB distribution has 2 parameters.

**Comment by vitkl** [comment]
I don't know if this is addressed but I will close it
