### ISSUE TITLE
run_regression out of memory for only 19k cells

### ISSUE THREAD

**Issue by bio-ruxandra-tesloianu** [BayraktarLab/cell2location#48]
I tried running the run_regression model on a reference dataset of 19k cells. However, I got a memory error. 

RuntimeError: CUDA out of memory. Tried to allocate 2.48 GiB (GPU 0; 31.75 GiB total capacity; 23.38 GiB already allocated; 2.46 GiB free; 27.29 GiB reserved in total by PyTorch)

**Comment by vitkl** [comment]
Looks like your GPU device run out of memory. Which `run_regression` options are you using?

**Comment by bio-ruxandra-tesloianu** [comment]
'tech_name_col': None,

                    'stratify_cv': 'annotation_1', # stratify cross-validation by cell type annotation

                    'n_epochs': 100, 'minibatch_size': 1024, 'learning_rate': 0.01,

                    'use_cuda': True, # use GPU?

                    'train_proportion': 0.9, # proportion of cells in the training set (for cross-validation)
                    'l2_weight': True,  # uses defaults for the model

**Comment by vitkl** [comment]
Yes, please try on a different GPU device which has more memory available (or
later when it has). With these parameters and data size, you should need
only about 3-4GB of GPU memory.
