### ISSUE TITLE
error run_regression model

### ISSUE THREAD

**Issue by bio-ruxandra-tesloianu** [BayraktarLab/cell2location#49]
Was wondering if you have any insight into where this is coming from. The model run fine and this happened at the plotting stage

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-615ed93ddc7c> in <module>
     29 
     30                    export_args={'path': results_folder + 'regression_model/', # where to save results
---> 31                                 'save_model': True, # save pytorch model?
     32                                 })
     33 

~/ENTER/envs/cellpymc/lib/python3.7/site-packages/cell2location/run_regression.py in run_regression(sc_data, model_name, verbose, return_all, train_args, model_kwargs, posterior_args, export_args)
    248         for tr in mod.validation_hist.values():
    249             deriv = np.gradient(tr, 1)
--> 250             new_n_epochs.append(np.max(np.arange(deriv.shape[0])[(deriv < 0)]))
    251         new_n_epochs = np.min(new_n_epochs) + 1
    252 

<__array_function__ internals> in amax(*args, **kwargs)

~/ENTER/envs/cellpymc/lib/python3.7/site-packages/numpy/core/fromnumeric.py in amax(a, axis, out, keepdims, initial, where)
   2732     """
   2733     return _wrapreduction(a, np.maximum, 'max', axis, None, out,
-> 2734                           keepdims=keepdims, initial=initial, where=where)
   2735 
   2736 

~/ENTER/envs/cellpymc/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85                 return reduction(axis=axis, out=out, **passkwargs)
     86 
---> 87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     88 
     89 

ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by vitkl** [comment]
So, @bio-ruxandra-tesloianu is this the solution?

**Comment by bio-ruxandra-tesloianu** [comment]
yes, thanks a lot
