### ISSUE TITLE
pip install git+https://github.com/BayraktarLab/cell2location.git  Command error

### ISSUE THREAD

**Issue by yangxueqianR** [BayraktarLab/cell2location#51]
Hello, I according to your side after all tutorials with conda created a virtual environment, when to PIP install git+https://github.com/BayraktarLab/cell2location.git, his error display the error:RPC failed; Result =35, HTTP code = 0 fatal: The remote end hung up unexpectedly.
How to solve this problem

**Comment by vitkl** [comment]
@yangxueqianR Thanks for using cell2location! Did you find a solution to this problem? Could be just temporary unstable network connection of your server or unusual git settings (see https://stackoverflow.com/a/6849424).
