### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pygpu (from versions: none)

### ISSUE THREAD

**Issue by nrosewick** [BayraktarLab/cell2location#56]
I followed the instruction ton install cell2location but at the `pip install git+https://github.com/BayraktarLab/cell2location.git` step I got this error :

```
Collecting git+https://github.com/BayraktarLab/cell2location.git
  Cloning https://github.com/BayraktarLab/cell2location.git to /tmp/pip-req-build-_9qxj1su
Collecting pymc3
  Using cached pymc3-3.11.2-py3-none-any.whl (869 kB)
Collecting torch
  Using cached torch-1.9.0-cp37-cp37m-manylinux1_x86_64.whl (831.4 MB)
Processing /home/nicolas/.cache/pip/wheels/26/68/6f/745330367ce7822fe0cd863712858151f5723a0a5e322cc144/Theano-1.0.5-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement pygpu (from cell2location==0.5) (from versions: none)
ERROR: No matching distribution found for pygpu (from cell2location==0.5)
```
I'm using python 3.7.3 through anaconda. 

Looking in the cellpymv environment, pygpu is well installed though...

Any idea how to solve this ?

Thanks

**Comment by vitkl** [comment]
Hi @nrosewick 

Did you activate conda environment before running `pip install git+https://github.com/BayraktarLab/cell2location.git`?

There might also be an issue with pip using the correct environment to install/load. I had a similar issue which was resolved by telling pip to never use user site:

```python
export PYTHONNOUSERSITE="randomletters"
```

**Comment by nrosewick** [comment]
Hi @vitkl ,

Thanks for the prompt reply. It was indeed an issue with pip. After executing `export` command, everything worked fine.

Thanks
